//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XINCIDENTModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENTCATEGORYDESCRIPTION
    {
        public int IncidentCategoryDescriptionID { get; set; }
        public int IncidentCategoryID { get; set; }
        public string IncidentCategoryGUID { get; set; }
        public int DescriptionID { get; set; }
        public string DescriptionGUID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual INCIDENTCATEGORY INCIDENTCATEGORY { get; set; }
    }
}
