//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XINCIDENTModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENTFORASSET
    {
        public int AssetIncidentID { get; set; }
        public string AssetIncidentGUID { get; set; }
        public int AssetID { get; set; }
        public string AssetGUID { get; set; }
        public string AssetIncidentRelationship { get; set; }
        public string AssetIncidentDescription { get; set; }
        public int IncidentID { get; set; }
        public string IncidentGUID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public string notes { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> VocabularyID { get; set; }
    
        public virtual INCIDENT INCIDENT { get; set; }
    }
}
