//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XINCIDENTModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class INCIDENTIMPACTINTEGRITYVARIETY
    {
        public int IncidentImpactIntegrityVarietyID { get; set; }
        public string IncidentImpactIntegrityVarietyName { get; set; }
        public string IncidentImpactIntegrityVarietyDescription { get; set; }
    }
}
