//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOVALModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OVALMESSAGETYPEFOROVALSYSTEMOBJECT
    {
        public int OVALSystemObjectID { get; set; }
        public int MessageTypeID { get; set; }
    
        public virtual OVALMESSAGETYPE OVALMESSAGETYPE { get; set; }
    }
}
