//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOVALModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OVALCRITERIATYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OVALCRITERIATYPE()
        {
            this.OVALCRITERIATYPEFOROVALDEFINITIONTYPE = new HashSet<OVALCRITERIATYPEFOROVALDEFINITIONTYPE>();
            this.OVALCRITERIONTYPE = new HashSet<OVALCRITERIONTYPE>();
        }
    
        public int OVALCriteriaTypeID { get; set; }
        public int OperatorEnumerationID { get; set; }
        public string OperatorValue { get; set; }
        public Nullable<bool> negate { get; set; }
        public int ResultEnumerationID { get; set; }
        public Nullable<bool> applicability_check { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OVALCRITERIATYPEFOROVALDEFINITIONTYPE> OVALCRITERIATYPEFOROVALDEFINITIONTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OVALCRITERIONTYPE> OVALCRITERIONTYPE { get; set; }
    }
}
