//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOVALModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OVALCRITERIONTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OVALCRITERIONTYPE()
        {
            this.OVALCRITERIATYPE = new HashSet<OVALCRITERIATYPE>();
        }
    
        public int OVALCriterionTypeID { get; set; }
        public Nullable<int> OVALTestID { get; set; }
        public string OVALTestIDPattern { get; set; }
        public int OVALTestVersion { get; set; }
        public Nullable<int> variable_instance { get; set; }
        public Nullable<bool> negate { get; set; }
        public int ResultEnumerationID { get; set; }
        public Nullable<bool> applicability_check { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OVALCRITERIATYPE> OVALCRITERIATYPE { get; set; }
    }
}
