//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOVALModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OVALDEFINITIONCHANGES
    {
        public int OVALDefinitionChangesID { get; set; }
        public Nullable<int> OVALDefinitionID { get; set; }
        public Nullable<int> OVALDefinitionChangeID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<int> OrganisationID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual OVALDEFINITIONCHANGE OVALDEFINITIONCHANGE { get; set; }
        public virtual OVALDEFINITION OVALDEFINITION { get; set; }
    }
}
