//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOVALModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OVALITEMSIMPLEBASE
    {
        public int OVALItemSimpleBaseID { get; set; }
        public int OVALItemAttributeGroupID { get; set; }
        public string EntityValue { get; set; }
    
        public virtual OVALITEMATTRIBUTEGROUP OVALITEMATTRIBUTEGROUP { get; set; }
    }
}
