//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOVALModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OVALSTATE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OVALSTATE()
        {
            this.OVALSTATEFOROVALTEST = new HashSet<OVALSTATEFOROVALTEST>();
            this.OVALSTATERECORDFOROVALSTATE = new HashSet<OVALSTATERECORDFOROVALSTATE>();
        }
    
        public int OVALStateID { get; set; }
        public string OVALStateIDPattern { get; set; }
        public Nullable<int> OVALStateVersion { get; set; }
        public Nullable<int> OVALStateSimpleBaseID { get; set; }
        public Nullable<int> OVALStateComplexBaseID { get; set; }
        public Nullable<int> OVALStateTypeID { get; set; }
        public string DataTypeName { get; set; }
        public Nullable<int> OperatorEnumerationID { get; set; }
        public string comment { get; set; }
        public Nullable<bool> deprecated { get; set; }
        public string notes { get; set; }
        public string signature { get; set; }
        public Nullable<int> OVALNamespaceID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<int> RepositoryID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual OVALNAMESPACE OVALNAMESPACE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OVALSTATEFOROVALTEST> OVALSTATEFOROVALTEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OVALSTATERECORDFOROVALSTATE> OVALSTATERECORDFOROVALSTATE { get; set; }
    }
}
