//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XOVALModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XOVALEntities : DbContext
    {
        public XOVALEntities()
            : base("name=XOVALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OPERATORENUMERATION> OPERATORENUMERATION { get; set; }
        public virtual DbSet<OVALBEHAVIOR> OVALBEHAVIOR { get; set; }
        public virtual DbSet<OVALBEHAVIORFOROVALOBJECT> OVALBEHAVIORFOROVALOBJECT { get; set; }
        public virtual DbSet<OVALCLASSDIRECTIVES> OVALCLASSDIRECTIVES { get; set; }
        public virtual DbSet<OVALCLASSDIRECTIVESFOROVALDIRECTIVES> OVALCLASSDIRECTIVESFOROVALDIRECTIVES { get; set; }
        public virtual DbSet<OVALCLASSENUMERATION> OVALCLASSENUMERATION { get; set; }
        public virtual DbSet<OVALCOMPONENTGROUP> OVALCOMPONENTGROUP { get; set; }
        public virtual DbSet<OVALCRITERIA> OVALCRITERIA { get; set; }
        public virtual DbSet<OVALCRITERIACRITERION> OVALCRITERIACRITERION { get; set; }
        public virtual DbSet<OVALCRITERIAEXTENDDEFINITION> OVALCRITERIAEXTENDDEFINITION { get; set; }
        public virtual DbSet<OVALCRITERIAFOROVALCRITERIA> OVALCRITERIAFOROVALCRITERIA { get; set; }
        public virtual DbSet<OVALCRITERIATYPE> OVALCRITERIATYPE { get; set; }
        public virtual DbSet<OVALCRITERIATYPEFOROVALDEFINITIONTYPE> OVALCRITERIATYPEFOROVALDEFINITIONTYPE { get; set; }
        public virtual DbSet<OVALCRITERION> OVALCRITERION { get; set; }
        public virtual DbSet<OVALCRITERIONTYPE> OVALCRITERIONTYPE { get; set; }
        public virtual DbSet<OVALDEFAULTDIRECTIVES> OVALDEFAULTDIRECTIVES { get; set; }
        public virtual DbSet<OVALDEFINITIONCCE> OVALDEFINITIONCCE { get; set; }
        public virtual DbSet<OVALDEFINITIONCHANGE> OVALDEFINITIONCHANGE { get; set; }
        public virtual DbSet<OVALDEFINITIONCHANGES> OVALDEFINITIONCHANGES { get; set; }
        public virtual DbSet<OVALDEFINITIONCPE> OVALDEFINITIONCPE { get; set; }
        public virtual DbSet<OVALDEFINITIONFAMILY> OVALDEFINITIONFAMILY { get; set; }
        public virtual DbSet<OVALDEFINITIONORGANISATION> OVALDEFINITIONORGANISATION { get; set; }
        public virtual DbSet<OVALDEFINITIONPLATFORM> OVALDEFINITIONPLATFORM { get; set; }
        public virtual DbSet<OVALDEFINITIONPRODUCT> OVALDEFINITIONPRODUCT { get; set; }
        public virtual DbSet<OVALDEFINITIONREFERENCE> OVALDEFINITIONREFERENCE { get; set; }
        public virtual DbSet<OVALDEFINITIONS> OVALDEFINITIONS { get; set; }
        public virtual DbSet<OVALDEFINITIONSTATUS> OVALDEFINITIONSTATUS { get; set; }
        public virtual DbSet<OVALDEFINITIONTAG> OVALDEFINITIONTAG { get; set; }
        public virtual DbSet<OVALDEFINITIONTYPE> OVALDEFINITIONTYPE { get; set; }
        public virtual DbSet<OVALDEFINITIONTYPEFOROVALSYSTEMTYPE> OVALDEFINITIONTYPEFOROVALSYSTEMTYPE { get; set; }
        public virtual DbSet<OVALDEFINITIONVULNERABILITY> OVALDEFINITIONVULNERABILITY { get; set; }
        public virtual DbSet<OVALDIRECTIVE> OVALDIRECTIVE { get; set; }
        public virtual DbSet<OVALDIRECTIVES> OVALDIRECTIVES { get; set; }
        public virtual DbSet<OVALDIRECTIVESTYPE> OVALDIRECTIVESTYPE { get; set; }
        public virtual DbSet<OVALENTITYATTRIBUTEGROUP> OVALENTITYATTRIBUTEGROUP { get; set; }
        public virtual DbSet<OVALENTITYCOMPLEXBASE> OVALENTITYCOMPLEXBASE { get; set; }
        public virtual DbSet<OVALENTITYSIMPLEBASE> OVALENTITYSIMPLEBASE { get; set; }
        public virtual DbSet<OVALEXTENSIONPOINT> OVALEXTENSIONPOINT { get; set; }
        public virtual DbSet<OVALEXTENSIONPOINTFOROVALGENERATORTYPE> OVALEXTENSIONPOINTFOROVALGENERATORTYPE { get; set; }
        public virtual DbSet<OVALEXTENSIONPOINTFORSYSTEMINFO> OVALEXTENSIONPOINTFORSYSTEMINFO { get; set; }
        public virtual DbSet<OVALFILTER> OVALFILTER { get; set; }
        public virtual DbSet<OVALFILTERFOROVALSET> OVALFILTERFOROVALSET { get; set; }
        public virtual DbSet<OVALGENERATORTYPE> OVALGENERATORTYPE { get; set; }
        public virtual DbSet<OVALITEM> OVALITEM { get; set; }
        public virtual DbSet<OVALITEMATTRIBUTEGROUP> OVALITEMATTRIBUTEGROUP { get; set; }
        public virtual DbSet<OVALITEMCOMPLEXBASE> OVALITEMCOMPLEXBASE { get; set; }
        public virtual DbSet<OVALITEMFOROVALSYSTEMOBJECT> OVALITEMFOROVALSYSTEMOBJECT { get; set; }
        public virtual DbSet<OVALITEMSIMPLEBASE> OVALITEMSIMPLEBASE { get; set; }
        public virtual DbSet<OVALLITERALCOMPONENT> OVALLITERALCOMPONENT { get; set; }
        public virtual DbSet<OVALLITERALCOMPONENTFOROVALCOMPONENTGROUP> OVALLITERALCOMPONENTFOROVALCOMPONENTGROUP { get; set; }
        public virtual DbSet<OVALMESSAGETYPE> OVALMESSAGETYPE { get; set; }
        public virtual DbSet<OVALMESSAGETYPEFOROVALSYSTEMOBJECT> OVALMESSAGETYPEFOROVALSYSTEMOBJECT { get; set; }
        public virtual DbSet<OVALMESSAGETYPEFOROVALTESTEDITEM> OVALMESSAGETYPEFOROVALTESTEDITEM { get; set; }
        public virtual DbSet<OVALMESSAGETYPEFOROVALTESTTYPE> OVALMESSAGETYPEFOROVALTESTTYPE { get; set; }
        public virtual DbSet<OVALNAMESPACE> OVALNAMESPACE { get; set; }
        public virtual DbSet<OVALOBJECT> OVALOBJECT { get; set; }
        public virtual DbSet<OVALOBJECTCOMPONENT> OVALOBJECTCOMPONENT { get; set; }
        public virtual DbSet<OVALOBJECTCOMPONENTFOROVALCOMPONENTGROUP> OVALOBJECTCOMPONENTFOROVALCOMPONENTGROUP { get; set; }
        public virtual DbSet<OVALOBJECTDATATYPE> OVALOBJECTDATATYPE { get; set; }
        public virtual DbSet<OVALOBJECTFIELD> OVALOBJECTFIELD { get; set; }
        public virtual DbSet<OVALOBJECTFIELDFOROVALOBJECTRECORD> OVALOBJECTFIELDFOROVALOBJECTRECORD { get; set; }
        public virtual DbSet<OVALOBJECTFILE> OVALOBJECTFILE { get; set; }
        public virtual DbSet<OVALOBJECTFOROVALSET> OVALOBJECTFOROVALSET { get; set; }
        public virtual DbSet<OVALOBJECTFOROVALTEST> OVALOBJECTFOROVALTEST { get; set; }
        public virtual DbSet<OVALOBJECTRECORD> OVALOBJECTRECORD { get; set; }
        public virtual DbSet<OVALOBJECTRECORDFOROVALOBJECT> OVALOBJECTRECORDFOROVALOBJECT { get; set; }
        public virtual DbSet<OVALOBJECTTAG> OVALOBJECTTAG { get; set; }
        public virtual DbSet<OVALOBJECTWINDOWSREGISTRYKEY> OVALOBJECTWINDOWSREGISTRYKEY { get; set; }
        public virtual DbSet<OVALRESULTS> OVALRESULTS { get; set; }
        public virtual DbSet<OVALRESULTSTYPE> OVALRESULTSTYPE { get; set; }
        public virtual DbSet<OVALSET> OVALSET { get; set; }
        public virtual DbSet<OVALSTATE> OVALSTATE { get; set; }
        public virtual DbSet<OVALSTATECOMPLEXBASE> OVALSTATECOMPLEXBASE { get; set; }
        public virtual DbSet<OVALSTATEFIELD> OVALSTATEFIELD { get; set; }
        public virtual DbSet<OVALSTATEFIELDFOROVALSTATERECORD> OVALSTATEFIELDFOROVALSTATERECORD { get; set; }
        public virtual DbSet<OVALSTATEFOROVALTEST> OVALSTATEFOROVALTEST { get; set; }
        public virtual DbSet<OVALSTATERECORD> OVALSTATERECORD { get; set; }
        public virtual DbSet<OVALSTATERECORDFOROVALSTATE> OVALSTATERECORDFOROVALSTATE { get; set; }
        public virtual DbSet<OVALSTATESIMPLEBASE> OVALSTATESIMPLEBASE { get; set; }
        public virtual DbSet<OVALSTATETYPE> OVALSTATETYPE { get; set; }
        public virtual DbSet<OVALSYSTEMCHARACTERISTICS> OVALSYSTEMCHARACTERISTICS { get; set; }
        public virtual DbSet<OVALSYSTEMOBJECT> OVALSYSTEMOBJECT { get; set; }
        public virtual DbSet<OVALSYSTEMTYPE> OVALSYSTEMTYPE { get; set; }
        public virtual DbSet<OVALTEST> OVALTEST { get; set; }
        public virtual DbSet<OVALTESTDATATYPE> OVALTESTDATATYPE { get; set; }
        public virtual DbSet<OVALTESTEDITEM> OVALTESTEDITEM { get; set; }
        public virtual DbSet<OVALTESTEDVARIABLE> OVALTESTEDVARIABLE { get; set; }
        public virtual DbSet<OVALTESTFOROVALTESTS> OVALTESTFOROVALTESTS { get; set; }
        public virtual DbSet<OVALTESTS> OVALTESTS { get; set; }
        public virtual DbSet<OVALTESTTAG> OVALTESTTAG { get; set; }
        public virtual DbSet<OVALTESTTYPE> OVALTESTTYPE { get; set; }
        public virtual DbSet<OVALTESTTYPEFOROVALSYSTEMTYPE> OVALTESTTYPEFOROVALSYSTEMTYPE { get; set; }
        public virtual DbSet<OVALVARIABLE> OVALVARIABLE { get; set; }
        public virtual DbSet<OVALVARIABLECOMPONENT> OVALVARIABLECOMPONENT { get; set; }
        public virtual DbSet<OVALVARIABLECOMPONENTFOROVALCOMPONENTGROUP> OVALVARIABLECOMPONENTFOROVALCOMPONENTGROUP { get; set; }
        public virtual DbSet<OVALVARIABLEDATATYPE> OVALVARIABLEDATATYPE { get; set; }
        public virtual DbSet<OVALVARIABLEFOROVALVARIABLES> OVALVARIABLEFOROVALVARIABLES { get; set; }
        public virtual DbSet<OVALVARIABLES> OVALVARIABLES { get; set; }
        public virtual DbSet<OVALVARIABLETAG> OVALVARIABLETAG { get; set; }
        public virtual DbSet<OVALVARIABLETYPE> OVALVARIABLETYPE { get; set; }
        public virtual DbSet<OVALVARIABLEVALUE> OVALVARIABLEVALUE { get; set; }
        public virtual DbSet<OVALVARIABLEVALUEFOROVALSYSTEMOBJECT> OVALVARIABLEVALUEFOROVALSYSTEMOBJECT { get; set; }
        public virtual DbSet<OVALDEFINITION> OVALDEFINITION { get; set; }
    }
}
