//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIONTAKEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTIONTAKEN()
        {
            this.ACTIONTAKENFORINCIDENT = new HashSet<ACTIONTAKENFORINCIDENT>();
            this.ACTIONTAKENFORTHREATCAMPAIGN = new HashSet<ACTIONTAKENFORTHREATCAMPAIGN>();
        }
    
        public int ActionTakenID { get; set; }
        public string ActionTakenGUID { get; set; }
        public string ActionName { get; set; }
        public string ActionDescription { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIONTAKENFORINCIDENT> ACTIONTAKENFORINCIDENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIONTAKENFORTHREATCAMPAIGN> ACTIONTAKENFORTHREATCAMPAIGN { get; set; }
    }
}
