//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALGORITHM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALGORITHM()
        {
            this.ENCODINGALGORITHM = new HashSet<ENCODINGALGORITHM>();
        }
    
        public int AlgorithmID { get; set; }
        public string AlgorithmName { get; set; }
        public string AlgorithmVersion { get; set; }
        public Nullable<int> AlgorithmVersionID { get; set; }
        public string AlgorithmDescription { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<int> TrustLevelID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual TRUSTLEVEL TRUSTLEVEL { get; set; }
        public virtual VERSION VERSION { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENCODINGALGORITHM> ENCODINGALGORITHM { get; set; }
    }
}
