//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIFUNCTION
    {
        public int APIFunctionID { get; set; }
        public string APIFunctionGUID { get; set; }
        public int APIID { get; set; }
        public int FunctionID { get; set; }
        public string Function_Name { get; set; }
        public string Normalized_Function_Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public string APIFunctionDescription { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
    
        public virtual API API { get; set; }
        public virtual CREATIONOBJECT CREATIONOBJECT { get; set; }
        public virtual FUNCTION FUNCTION { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
