//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSETINFORMATION
    {
        public int AssetInformationID { get; set; }
        public string hostname { get; set; }
        public string netbios { get; set; }
        public string hosttype { get; set; }
        public int JobID { get; set; }
        public string information { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
    }
}
