//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCEREFERENCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CCEREFERENCE()
        {
            this.CCEREFERENCEFORCCE = new HashSet<CCEREFERENCEFORCCE>();
            this.CCERESOURCEFORCCEREFERENCE = new HashSet<CCERESOURCEFORCCEREFERENCE>();
        }
    
        public int CCEReferenceID { get; set; }
        public string resource_id { get; set; }
        public string ReferenceText { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual REFERENCE REFERENCE { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCEREFERENCEFORCCE> CCEREFERENCEFORCCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CCERESOURCEFORCCEREFERENCE> CCERESOURCEFORCCEREFERENCE { get; set; }
    }
}
