//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHANGERECORD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHANGERECORD()
        {
            this.ACCOUNTCHANGERECORD = new HashSet<ACCOUNTCHANGERECORD>();
            this.ASSETCHANGERECORD = new HashSet<ASSETCHANGERECORD>();
            this.REFERENCECHANGERECORD = new HashSet<REFERENCECHANGERECORD>();
        }
    
        public int ChangeRecordID { get; set; }
        public string ChangeRecordGUID { get; set; }
        public string ChangedObjectGUID { get; set; }
        public string BeforeChange { get; set; }
        public string AfterChange { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> ConfidenceLevelID { get; set; }
        public Nullable<int> ConfidenceReasonID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNTCHANGERECORD> ACCOUNTCHANGERECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETCHANGERECORD> ASSETCHANGERECORD { get; set; }
        public virtual CONFIDENCELEVEL CONFIDENCELEVEL { get; set; }
        public virtual CONFIDENCEREASON CONFIDENCEREASON { get; set; }
        public virtual CREATIONOBJECT CREATIONOBJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REFERENCECHANGERECORD> REFERENCECHANGERECORD { get; set; }
    }
}
