//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRESSIONMECHANISM
    {
        public int CompressionMechanismID { get; set; }
        public Nullable<int> MechanismID { get; set; }
    
        public virtual MECHANISM MECHANISM { get; set; }
    }
}
