//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COOKIEAPPLICATION
    {
        public int CookieApplicationID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string ApplicationGUID { get; set; }
        public string CookieApplicationRelationship { get; set; }
        public string CookieApplicationDescription { get; set; }
        public Nullable<int> CookieID { get; set; }
        public string CookieGUID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<int> VocabularyID { get; set; }
    
        public virtual APPLICATION APPLICATION { get; set; }
        public virtual COOKIE COOKIE { get; set; }
        public virtual CREATIONOBJECT CREATIONOBJECT { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
