//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTRYLOCALE
    {
        public int CountryLocaleID { get; set; }
        public int CountryID { get; set; }
        public int LocaleID { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual LOCALE LOCALE { get; set; }
    }
}
