//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPEFORAPPLICATION
    {
        public int ApplicationCPEID { get; set; }
        public int ApplicationID { get; set; }
        public string ApplicationGUID { get; set; }
        public int CPEID { get; set; }
        public Nullable<System.DateTimeOffset> CreationDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> LastCheckedDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<int> CollectionMethodID { get; set; }
        public Nullable<int> ConfidenceLevelID { get; set; }
    
        public virtual APPLICATION APPLICATION { get; set; }
        public virtual COLLECTIONMETHOD COLLECTIONMETHOD { get; set; }
        public virtual CONFIDENCELEVEL CONFIDENCELEVEL { get; set; }
        public virtual CPE CPE { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
