//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPELOGICALTEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPELOGICALTEST()
        {
            this.VULNERABLECONFIGURATIONCPE = new HashSet<VULNERABLECONFIGURATIONCPE>();
        }
    
        public int CPELogicalTestID { get; set; }
        public Nullable<bool> negate { get; set; }
        public Nullable<int> OperatorEnumerationID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> VocabularyID { get; set; }
    
        public virtual OPERATORENUMERATION OPERATORENUMERATION { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VULNERABLECONFIGURATIONCPE> VULNERABLECONFIGURATIONCPE { get; set; }
    }
}
