//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWEATTACKCONSEQUENCE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CWEATTACKCONSEQUENCE()
        {
            this.CWEATTACKCONSEQUENCESCOPE = new HashSet<CWEATTACKCONSEQUENCESCOPE>();
            this.CWEATTACKCONSEQUENCETAG = new HashSet<CWEATTACKCONSEQUENCETAG>();
            this.CWEATTACKTECHNICALIMPACT = new HashSet<CWEATTACKTECHNICALIMPACT>();
        }
    
        public int CWEAttackConsequenceID { get; set; }
        public string CWEID { get; set; }
        public int CWEAttackConsequenceOrder { get; set; }
        public string Consequence_Note { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> ConfidenceLevelID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual CONFIDENCELEVEL CONFIDENCELEVEL { get; set; }
        public virtual CWE CWE { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CWEATTACKCONSEQUENCESCOPE> CWEATTACKCONSEQUENCESCOPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CWEATTACKCONSEQUENCETAG> CWEATTACKCONSEQUENCETAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CWEATTACKTECHNICALIMPACT> CWEATTACKTECHNICALIMPACT { get; set; }
    }
}
