//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWEDETECTIONMETHOD
    {
        public int CWEDetectionMethodID { get; set; }
        public string CWEDetectionMethodGUID { get; set; }
        public string CWEID { get; set; }
        public string CWEGUID { get; set; }
        public int DetectionMethodID { get; set; }
        public string DetectionMethodGUID { get; set; }
        public string CWEDetectionMethodDescription { get; set; }
        public string CWEDetectionMethodEffectiveness { get; set; }
        public string CWEDetectionMethodEffectivenessNotes { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<int> TrustLevelID { get; set; }
        public Nullable<int> TrustReasonID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
    
        public virtual CWE CWE { get; set; }
        public virtual DETECTIONMETHOD DETECTIONMETHOD { get; set; }
        public virtual TRUSTLEVEL TRUSTLEVEL { get; set; }
        public virtual TRUSTREASON TRUSTREASON { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
