//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWEMODEOFINTRODUCTIONTAG
    {
        public int CWEModeOfIntroductionTagID { get; set; }
        public Nullable<int> CWEModeOfIntroductionID { get; set; }
        public Nullable<int> TagID { get; set; }
    
        public virtual CWEMODEOFINTRODUCTION CWEMODEOFINTRODUCTION { get; set; }
        public virtual TAG TAG { get; set; }
    }
}
