//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWETHEORETICALNOTE
    {
        public int CWETheoreticalNoteID { get; set; }
        public string CWEID { get; set; }
        public int TheoreticalNoteID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
    
        public virtual CWE CWE { get; set; }
        public virtual THEORETICALNOTE THEORETICALNOTE { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
