//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESCRIPTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DESCRIPTION()
        {
            this.ACTIONDESCRIPTION = new HashSet<ACTIONDESCRIPTION>();
            this.CONTROLDESCRIPTION = new HashSet<CONTROLDESCRIPTION>();
            this.ENTITYDESCRIPTION = new HashSet<ENTITYDESCRIPTION>();
            this.FILEDESCRIPTION = new HashSet<FILEDESCRIPTION>();
            this.FINDINGDESCRIPTION = new HashSet<FINDINGDESCRIPTION>();
            this.HEADERDESCRIPTION = new HashSet<HEADERDESCRIPTION>();
            this.HTTPHEADERDESCRIPTION = new HashSet<HTTPHEADERDESCRIPTION>();
            this.METHODOLOGYDESCRIPTION = new HashSet<METHODOLOGYDESCRIPTION>();
            this.METRICDESCRIPTION = new HashSet<METRICDESCRIPTION>();
            this.MODELDESCRIPTION = new HashSet<MODELDESCRIPTION>();
            this.NETWORKZONEDESCRIPTION = new HashSet<NETWORKZONEDESCRIPTION>();
            this.PARAMETERDESCRIPTION = new HashSet<PARAMETERDESCRIPTION>();
            this.PERMISSIONDESCRIPTION = new HashSet<PERMISSIONDESCRIPTION>();
            this.PHYSICALLOCATIONDESCRIPTION = new HashSet<PHYSICALLOCATIONDESCRIPTION>();
            this.PROJECTDESCRIPTION = new HashSet<PROJECTDESCRIPTION>();
            this.REFERENCEDESCRIPTION = new HashSet<REFERENCEDESCRIPTION>();
            this.REQUIREMENTDESCRIPTION = new HashSet<REQUIREMENTDESCRIPTION>();
            this.SCRIPTDESCRIPTION = new HashSet<SCRIPTDESCRIPTION>();
            this.SECTIONDESCRIPTION = new HashSet<SECTIONDESCRIPTION>();
            this.SECURITYMETRICDESCRIPTION = new HashSet<SECURITYMETRICDESCRIPTION>();
            this.SECURITYPRINCIPLEDESCRIPTION = new HashSet<SECURITYPRINCIPLEDESCRIPTION>();
            this.STAGEDESCRIPTION = new HashSet<STAGEDESCRIPTION>();
            this.TASKDESCRIPTION = new HashSet<TASKDESCRIPTION>();
            this.TOOLINFORMATIONDESCRIPTION = new HashSet<TOOLINFORMATIONDESCRIPTION>();
            this.VOCABULARYDESCRIPTION = new HashSet<VOCABULARYDESCRIPTION>();
        }
    
        public int DescriptionID { get; set; }
        public string DescriptionGUID { get; set; }
        public string DescriptionText { get; set; }
        public Nullable<int> LocaleID { get; set; }
        public Nullable<int> VersionID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<int> ConfidentialityLevelID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTIONDESCRIPTION> ACTIONDESCRIPTION { get; set; }
        public virtual CONFIDENTIALITYLEVEL CONFIDENTIALITYLEVEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROLDESCRIPTION> CONTROLDESCRIPTION { get; set; }
        public virtual CREATIONOBJECT CREATIONOBJECT { get; set; }
        public virtual LOCALE LOCALE { get; set; }
        public virtual VERSION VERSION { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTITYDESCRIPTION> ENTITYDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILEDESCRIPTION> FILEDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINDINGDESCRIPTION> FINDINGDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HEADERDESCRIPTION> HEADERDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTTPHEADERDESCRIPTION> HTTPHEADERDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<METHODOLOGYDESCRIPTION> METHODOLOGYDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<METRICDESCRIPTION> METRICDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MODELDESCRIPTION> MODELDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NETWORKZONEDESCRIPTION> NETWORKZONEDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARAMETERDESCRIPTION> PARAMETERDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERMISSIONDESCRIPTION> PERMISSIONDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHYSICALLOCATIONDESCRIPTION> PHYSICALLOCATIONDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTDESCRIPTION> PROJECTDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REFERENCEDESCRIPTION> REFERENCEDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUIREMENTDESCRIPTION> REQUIREMENTDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCRIPTDESCRIPTION> SCRIPTDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECTIONDESCRIPTION> SECTIONDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYMETRICDESCRIPTION> SECURITYMETRICDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYPRINCIPLEDESCRIPTION> SECURITYPRINCIPLEDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAGEDESCRIPTION> STAGEDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASKDESCRIPTION> TASKDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLINFORMATIONDESCRIPTION> TOOLINFORMATIONDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOCABULARYDESCRIPTION> VOCABULARYDESCRIPTION { get; set; }
    }
}
