//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEVICE()
        {
            this.ASSETDEVICE = new HashSet<ASSETDEVICE>();
            this.DEVICEBLACKLIST = new HashSet<DEVICEBLACKLIST>();
            this.DEVICEWHITELIST = new HashSet<DEVICEWHITELIST>();
            this.ENDPOINT = new HashSet<ENDPOINT>();
            this.EVENTCOLLECTIONMETHOD = new HashSet<EVENTCOLLECTIONMETHOD>();
            this.HARDWARE = new HashSet<HARDWARE>();
            this.MOBILEDEVICE = new HashSet<MOBILEDEVICE>();
            this.PERSONDEVICE = new HashSet<PERSONDEVICE>();
            this.PRODUCT = new HashSet<PRODUCT>();
        }
    
        public int DeviceID { get; set; }
        public string DeviceGUID { get; set; }
        public string Device_Type { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> OrganisationID { get; set; }
        public string Model { get; set; }
        public string Firmware_Version { get; set; }
        public Nullable<int> CPEID { get; set; }
        public string CPEName { get; set; }
        public string Serial_Number { get; set; }
        public string Description { get; set; }
        public Nullable<int> ClockSpeedFrequency { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETDEVICE> ASSETDEVICE { get; set; }
        public virtual CPE CPE { get; set; }
        public virtual ORGANISATION ORGANISATION { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEVICEBLACKLIST> DEVICEBLACKLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEVICEWHITELIST> DEVICEWHITELIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENDPOINT> ENDPOINT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTCOLLECTIONMETHOD> EVENTCOLLECTIONMETHOD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HARDWARE> HARDWARE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOBILEDEVICE> MOBILEDEVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONDEVICE> PERSONDEVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCT { get; set; }
    }
}
