//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIGITALSIGNATUREINFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIGITALSIGNATUREINFO()
        {
            this.DIGITALSIGNATURES = new HashSet<DIGITALSIGNATURES>();
        }
    
        public int DigitalSignatureInfoID { get; set; }
        public string Certificate_Issuer { get; set; }
        public Nullable<int> OrganisationID { get; set; }
        public string Certificate_Subject { get; set; }
        public string Signature_Description { get; set; }
        public Nullable<bool> signature_exists { get; set; }
        public Nullable<bool> signature_verified { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIGITALSIGNATURES> DIGITALSIGNATURES { get; set; }
    }
}
