//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTCATEGORY
    {
        public int DocumentCategoryID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual DOCUMENT DOCUMENT { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
