//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPE
    {
        public int DPEID { get; set; }
        public string CPEID { get; set; }
        public Nullable<int> CredentialID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<int> PortID { get; set; }
        public Nullable<int> ProtocolID { get; set; }
    
        public virtual CREDENTIAL CREDENTIAL { get; set; }
        public virtual PORT PORT { get; set; }
        public virtual PROTOCOL PROTOCOL { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
