//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAILFORORGANISATION
    {
        public string emailaddress { get; set; }
        public int OrganisationID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<int> ConfidenceLevelID { get; set; }
        public Nullable<int> TrustLevelID { get; set; }
    
        public virtual CONFIDENCELEVEL CONFIDENCELEVEL { get; set; }
        public virtual EMAIL EMAIL { get; set; }
        public virtual ORGANISATION ORGANISATION { get; set; }
        public virtual TRUSTLEVEL TRUSTLEVEL { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
