//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTITYDESCRIPTION
    {
        public int EntityDescriptionID { get; set; }
        public int EntityID { get; set; }
        public int DescriptionID { get; set; }
    
        public virtual DESCRIPTION DESCRIPTION { get; set; }
        public virtual ENTITY ENTITY { get; set; }
    }
}
