//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTRACTEDFEATURES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXTRACTEDFEATURES()
        {
            this.CODE = new HashSet<CODE>();
        }
    
        public int ExtractedFeaturesID { get; set; }
        public string ExtractedFeaturesGUID { get; set; }
        public string ExtractedStringsGUID { get; set; }
        public string ImportsGUID { get; set; }
        public string FunctionsGUID { get; set; }
        public string CodeSnippetsGUID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CODE> CODE { get; set; }
    }
}
