//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIXACTIONCOST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FIXACTIONCOST()
        {
            this.FIXACTIONFORINCIDENT = new HashSet<FIXACTIONFORINCIDENT>();
        }
    
        public int FixActionCostID { get; set; }
        public string cost_corrective_action { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIXACTIONFORINCIDENT> FIXACTIONFORINCIDENT { get; set; }
    }
}
