//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCTIONRELATIONSHIP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNCTIONRELATIONSHIP()
        {
            this.FUNCTIONRELATIONSHIPREFERENCE = new HashSet<FUNCTIONRELATIONSHIPREFERENCE>();
        }
    
        public int FunctionRelationshipID { get; set; }
        public string FunctionRelationshipGUID { get; set; }
        public int FunctionParentID { get; set; }
        public int FunctionSubjectID { get; set; }
        public string FunctionRelationshipDescription { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<int> ConfidenceLevelID { get; set; }
    
        public virtual CONFIDENCELEVEL CONFIDENCELEVEL { get; set; }
        public virtual FUNCTION FUNCTION { get; set; }
        public virtual FUNCTION FUNCTION1 { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUNCTIONRELATIONSHIPREFERENCE> FUNCTIONRELATIONSHIPREFERENCE { get; set; }
    }
}
