//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOSTENDPOINT
    {
        public int HostEndPointID { get; set; }
        public Nullable<int> HostPort { get; set; }
        public string HostProtocol { get; set; }
        public Nullable<int> HostID { get; set; }
        public string HostService { get; set; }
        public string HostVersion { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
    
        public virtual HOST HOST { get; set; }
    }
}
