//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTTPREQUESTLINE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HTTPREQUESTLINE()
        {
            this.HTTPCLIENTREQUEST = new HashSet<HTTPCLIENTREQUEST>();
        }
    
        public int HTTPRequestLineID { get; set; }
        public Nullable<int> HTTP_Method { get; set; }
        public string Value { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTimeOffset> CreationDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTTPCLIENTREQUEST> HTTPCLIENTREQUEST { get; set; }
        public virtual HTTPMETHOD HTTPMETHOD { get; set; }
    }
}
