//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IEXECACTION
    {
        public int IExecActionID { get; set; }
        public string Exec_Arguments { get; set; }
        public string Exec_Program_Path { get; set; }
        public string Exec_Working_Directory { get; set; }
        public Nullable<int> DirectoryID { get; set; }
        public string Exec_Program_Hashes { get; set; }
        public Nullable<int> HashListID { get; set; }
    }
}
