//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDICATOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INDICATOR()
        {
            this.INDICATORENVIRONMENT = new HashSet<INDICATORENVIRONMENT>();
            this.INDICATORTESTMECHANISM = new HashSet<INDICATORTESTMECHANISM>();
            this.INDICATOR1 = new HashSet<INDICATOR>();
            this.INDICATOR2 = new HashSet<INDICATOR>();
            this.INDICATORID1 = new HashSet<INDICATORID>();
        }
    
        public int IndicatorID { get; set; }
        public string IndicatorGUID { get; set; }
        public string IndicatorTitle { get; set; }
        public string IndicatorDescription { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> ConfidenceLevelID { get; set; }
        public string ConfidenceLevel { get; set; }
        public Nullable<int> ConfidenceReasonID { get; set; }
        public string LikelyImpact { get; set; }
        public string Producer { get; set; }
        public Nullable<bool> negate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<int> RepositoryID { get; set; }
        public Nullable<int> ImportanceID { get; set; }
    
        public virtual CONFIDENCELEVEL CONFIDENCELEVEL1 { get; set; }
        public virtual CONFIDENCEREASON CONFIDENCEREASON { get; set; }
        public virtual IMPORTANCE IMPORTANCE { get; set; }
        public virtual REPOSITORY REPOSITORY { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INDICATORENVIRONMENT> INDICATORENVIRONMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INDICATORTESTMECHANISM> INDICATORTESTMECHANISM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INDICATOR> INDICATOR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INDICATOR> INDICATOR2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INDICATORID> INDICATORID1 { get; set; }
    }
}
