//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class INJECTIONVECTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INJECTIONVECTOR()
        {
            this.INJECTIONVECTORFORATTACKPATTERN = new HashSet<INJECTIONVECTORFORATTACKPATTERN>();
        }
    
        public int InjectionVectorID { get; set; }
        public string InjectionVectorGUID { get; set; }
        public string InjectionVectorText { get; set; }
        public string InjectionVectorDescription { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
    
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INJECTIONVECTORFORATTACKPATTERN> INJECTIONVECTORFORATTACKPATTERN { get; set; }
    }
}
