//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERACTIONLEVEL
    {
        public int InteractionLevelID { get; set; }
        public string InteractionLevel1 { get; set; }
        public Nullable<int> VocabularyID { get; set; }
    
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
