//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISHOWMESSAGEACTION
    {
        public int IShowMessageActionID { get; set; }
        public string Show_Message_Body { get; set; }
        public string Show_Message_Title { get; set; }
    }
}
