//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRARIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIBRARIES()
        {
            this.BUILDINFORMATION = new HashSet<BUILDINFORMATION>();
        }
    
        public int LibrariesID { get; set; }
        public string LibrariesGUID { get; set; }
        public int LibraryID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BUILDINFORMATION> BUILDINFORMATION { get; set; }
    }
}
