//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATIONPOINT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCATIONPOINT()
        {
            this.LOCATIONPOINTFORASSET = new HashSet<LOCATIONPOINTFORASSET>();
            this.LOCATIONPOINTFORORGANISATION = new HashSet<LOCATIONPOINTFORORGANISATION>();
            this.LOCATIONPOINTFORPERSON = new HashSet<LOCATIONPOINTFORPERSON>();
        }
    
        public int LocationPointID { get; set; }
        public int latitude { get; set; }
        public int longitude { get; set; }
        public Nullable<int> elevation { get; set; }
        public Nullable<int> radius { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCATIONPOINTFORASSET> LOCATIONPOINTFORASSET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCATIONPOINTFORORGANISATION> LOCATIONPOINTFORORGANISATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOCATIONPOINTFORPERSON> LOCATIONPOINTFORPERSON { get; set; }
    }
}
