//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEASURESOURCETOOL
    {
        public int MeasureSourceID { get; set; }
        public int ToolInformationID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
    
        public virtual MEASURESOURCE MEASURESOURCE { get; set; }
        public virtual TOOLINFORMATION TOOLINFORMATION { get; set; }
    }
}
