//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class METHODOLOGYDESCRIPTION
    {
        public int MethodologyDescriptionID { get; set; }
        public int MethodologyID { get; set; }
        public int DescriptionID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> ValidityID { get; set; }
        public Nullable<int> VocabularyID { get; set; }
    
        public virtual CREATIONOBJECT CREATIONOBJECT { get; set; }
        public virtual DESCRIPTION DESCRIPTION { get; set; }
        public virtual METHODOLOGY METHODOLOGY { get; set; }
        public virtual VALIDITY VALIDITY { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
