//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class METHODOLOGYTEST
    {
        public int MethodologyTestID { get; set; }
        public string MethodologyTestGUID { get; set; }
        public Nullable<int> MethodologyID { get; set; }
        public string MethodologyGUID { get; set; }
        public Nullable<int> TestID { get; set; }
        public string TestGUID { get; set; }
        public string TestVocabularyID { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual METHODOLOGY METHODOLOGY { get; set; }
        public virtual TEST TEST { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
