//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MITIGATIONSTRATEGYFORMITIGATION
    {
        public int MitigationMitigationStrategyID { get; set; }
        public int MitigationID { get; set; }
        public string MitigationGUID { get; set; }
        public int MitigationStrategyID { get; set; }
        public string MitigationStrategyGUID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public int ConfidenceLevelID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual CONFIDENCELEVEL CONFIDENCELEVEL { get; set; }
        public virtual CREATIONOBJECT CREATIONOBJECT { get; set; }
        public virtual MITIGATION MITIGATION { get; set; }
        public virtual MITIGATIONSTRATEGY MITIGATIONSTRATEGY { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
