//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NETWORKCONNECTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NETWORKCONNECTION()
        {
            this.NETWORKCONNECTIONLAYER7 = new HashSet<NETWORKCONNECTIONLAYER7>();
        }
    
        public int NetworkConnectionID { get; set; }
        public string NetworkConnectionGUID { get; set; }
        public Nullable<bool> tls_used { get; set; }
        public Nullable<System.DateTimeOffset> Creation_Time { get; set; }
        public Nullable<int> ProtocolLayer3ID { get; set; }
        public string Layer3_Protocol { get; set; }
        public Nullable<int> ProtocolLayer4ID { get; set; }
        public string Layer4_Protocol { get; set; }
        public Nullable<int> ProtocolLayer7ID { get; set; }
        public string Layer7_Protocol { get; set; }
        public Nullable<int> SourceSocketAddressID { get; set; }
        public Nullable<int> SourceTCPStateID { get; set; }
        public string Source_TCP_State { get; set; }
        public Nullable<int> DestinationSocketAddressID { get; set; }
        public Nullable<int> DestinationTCPStateID { get; set; }
        public string Destination_TCP_State { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
    
        public virtual NETWORKCONNECTION NETWORKCONNECTION1 { get; set; }
        public virtual NETWORKCONNECTION NETWORKCONNECTION2 { get; set; }
        public virtual PROTOCOL PROTOCOL { get; set; }
        public virtual PROTOCOL PROTOCOL1 { get; set; }
        public virtual PROTOCOL PROTOCOL2 { get; set; }
        public virtual SOCKETADDRESS SOCKETADDRESS { get; set; }
        public virtual SOCKETADDRESS SOCKETADDRESS1 { get; set; }
        public virtual TCPSTATE TCPSTATE { get; set; }
        public virtual TCPSTATE TCPSTATE1 { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NETWORKCONNECTIONLAYER7> NETWORKCONNECTIONLAYER7 { get; set; }
    }
}
