//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NETWORKZONE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NETWORKZONE()
        {
            this.APPLICATIONNETWORKZONE = new HashSet<APPLICATIONNETWORKZONE>();
            this.ASSETNETWORKZONE = new HashSet<ASSETNETWORKZONE>();
            this.NETWORKZONEDESCRIPTION1 = new HashSet<NETWORKZONEDESCRIPTION>();
        }
    
        public int NetworkZoneID { get; set; }
        public string NetworkZoneGUID { get; set; }
        public Nullable<int> ZoneID { get; set; }
        public string ZoneGUID { get; set; }
        public string NetworkZoneName { get; set; }
        public string NetworkZoneDescription { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> ValidityID { get; set; }
        public Nullable<int> TrustLevelID { get; set; }
        public Nullable<int> TrustReasonID { get; set; }
        public Nullable<int> VocabularyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICATIONNETWORKZONE> APPLICATIONNETWORKZONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETNETWORKZONE> ASSETNETWORKZONE { get; set; }
        public virtual CREATIONOBJECT CREATIONOBJECT { get; set; }
        public virtual TRUSTLEVEL TRUSTLEVEL { get; set; }
        public virtual TRUSTREASON TRUSTREASON { get; set; }
        public virtual VALIDITY VALIDITY { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        public virtual ZONE ZONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NETWORKZONEDESCRIPTION> NETWORKZONEDESCRIPTION1 { get; set; }
    }
}
