//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NETWORKROUTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NETWORKROUTE()
        {
            this.NETWORKSUBNETROUTES = new HashSet<NETWORKSUBNETROUTES>();
        }
    
        public int NetworkRouteID { get; set; }
        public string NetworkRouteGUID { get; set; }
        public Nullable<int> NetRouteID { get; set; }
        public Nullable<bool> is_ipv6 { get; set; }
        public Nullable<bool> is_autoconfigure_address { get; set; }
        public Nullable<bool> is_immortal { get; set; }
        public Nullable<bool> is_loopback { get; set; }
        public Nullable<bool> is_publish { get; set; }
        public Nullable<int> DestinationAddressID { get; set; }
        public Nullable<int> OriginAddressID { get; set; }
        public Nullable<int> NetmaskID { get; set; }
        public Nullable<int> GatewayAddressID { get; set; }
        public Nullable<int> Metric { get; set; }
        public Nullable<int> NetworkRouteTypeID { get; set; }
        public string NetworkRouteType { get; set; }
        public Nullable<int> ProtocolID { get; set; }
        public string NetworkRouteProtocol { get; set; }
        public string NetworkRouteInterface { get; set; }
        public Nullable<int> PreferredLifetime { get; set; }
        public Nullable<int> ValidLifetime { get; set; }
        public Nullable<int> RouteAge { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual ADDRESS ADDRESS1 { get; set; }
        public virtual ADDRESS ADDRESS2 { get; set; }
        public virtual ADDRESS ADDRESS3 { get; set; }
        public virtual NETROUTE NETROUTE { get; set; }
        public virtual NETWORKROUTETYPE NETWORKROUTETYPE1 { get; set; }
        public virtual PROTOCOL PROTOCOL { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NETWORKSUBNETROUTES> NETWORKSUBNETROUTES { get; set; }
    }
}
