//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJECTIVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBJECTIVE()
        {
            this.CAPABILITYOBJECTIVE = new HashSet<CAPABILITYOBJECTIVE>();
            this.OBJECTIVETAG = new HashSet<OBJECTIVETAG>();
            this.SECURITYDOMAINOBJECTIVE = new HashSet<SECURITYDOMAINOBJECTIVE>();
            this.STANDARDOBJECTIVE = new HashSet<STANDARDOBJECTIVE>();
            this.STRATEGICOBJECTIVE = new HashSet<STRATEGICOBJECTIVE>();
            this.TACTICALOBJECTIVE = new HashSet<TACTICALOBJECTIVE>();
        }
    
        public int ObjectiveID { get; set; }
        public string ObjectiveGUID { get; set; }
        public Nullable<int> ObjectiveCategoryID { get; set; }
        public string ObjectiveVocabularyID { get; set; }
        public string ObjectiveName { get; set; }
        public string ObjectiveDescription { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAPABILITYOBJECTIVE> CAPABILITYOBJECTIVE { get; set; }
        public virtual OBJECTIVECATEGORY OBJECTIVECATEGORY { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBJECTIVETAG> OBJECTIVETAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYDOMAINOBJECTIVE> SECURITYDOMAINOBJECTIVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STANDARDOBJECTIVE> STANDARDOBJECTIVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STRATEGICOBJECTIVE> STRATEGICOBJECTIVE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACTICALOBJECTIVE> TACTICALOBJECTIVE { get; set; }
    }
}
