//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPCODEFORCPE
    {
        public string CPEID { get; set; }
        public int OpcodeID { get; set; }
    
        public virtual OPCODE OPCODE { get; set; }
    }
}
