//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWASPTOP10IMPACT
    {
        public int OWASPTOP10ID { get; set; }
        public int ImpactID { get; set; }
        public string ImpactSeverity { get; set; }
    
        public virtual IMPACT IMPACT { get; set; }
        public virtual OWASPTOP10 OWASPTOP10 { get; set; }
    }
}
