//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACKAGINGENCODING
    {
        public int PackagingEncodingID { get; set; }
        public string PackagingEncodingGUID { get; set; }
        public int PackagingID { get; set; }
        public string PackagingGUID { get; set; }
        public int EncodingID { get; set; }
        public string EncodingGUID { get; set; }
        public int LayerOrder { get; set; }
        public string algorithm { get; set; }
        public string character_set { get; set; }
        public Nullable<int> CharacterSetID { get; set; }
        public string custom_character_set_ref { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> CollectionMethodID { get; set; }
        public Nullable<int> CollectionToolID { get; set; }
        public Nullable<int> ConfidenceLevelID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual CHARACTERSET CHARACTERSET { get; set; }
        public virtual COLLECTIONMETHOD COLLECTIONMETHOD { get; set; }
        public virtual CONFIDENCELEVEL CONFIDENCELEVEL { get; set; }
        public virtual CREATIONOBJECT CREATIONOBJECT { get; set; }
        public virtual ENCODING ENCODING { get; set; }
        public virtual PACKAGING PACKAGING { get; set; }
        public virtual TOOL TOOL { get; set; }
    }
}
