//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONLICENSE
    {
        public int PersonLicenseID { get; set; }
        public int PersonID { get; set; }
        public string PersonGUID { get; set; }
        public int LicenseID { get; set; }
        public string LicenseGUID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual LICENSE LICENSE { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
