//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHYSICALLOCATIONTAG
    {
        public int PhysicalLocationTagID { get; set; }
        public Nullable<int> PhysicalLocationID { get; set; }
        public string PhysicalLocationGUID { get; set; }
        public Nullable<int> TagID { get; set; }
        public string TagGUID { get; set; }
        public Nullable<int> ConfidentialityLevelID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> ValidityID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual CONFIDENTIALITYLEVEL CONFIDENTIALITYLEVEL { get; set; }
        public virtual CREATIONOBJECT CREATIONOBJECT { get; set; }
        public virtual PHYSICALLOCATION PHYSICALLOCATION { get; set; }
        public virtual TAG TAG { get; set; }
        public virtual VALIDITY VALIDITY { get; set; }
    }
}
