//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJECT()
        {
            this.AUDIT = new HashSet<AUDIT>();
            this.INVESTIGATION = new HashSet<INVESTIGATION>();
            this.ORGANISATIONPROJECT = new HashSet<ORGANISATIONPROJECT>();
            this.PERSONFORPROJECT = new HashSet<PERSONFORPROJECT>();
            this.PROJECTDESCRIPTION1 = new HashSet<PROJECTDESCRIPTION>();
            this.PROJECTFINDING = new HashSet<PROJECTFINDING>();
            this.PROJECTFORAPPLICATION = new HashSet<PROJECTFORAPPLICATION>();
            this.PROJECTMAPPING = new HashSet<PROJECTMAPPING>();
            this.PROJECTMAPPING1 = new HashSet<PROJECTMAPPING>();
            this.PROJECTMETHODOLOGY = new HashSet<PROJECTMETHODOLOGY>();
            this.PROJECTPERSON = new HashSet<PROJECTPERSON>();
            this.PROJECTTAG = new HashSet<PROJECTTAG>();
            this.PROJECTTASK = new HashSet<PROJECTTASK>();
            this.SECURITYPROGRAMPROJECT = new HashSet<SECURITYPROGRAMPROJECT>();
            this.TASKFORPROJECT = new HashSet<TASKFORPROJECT>();
            this.TIMESHEET = new HashSet<TIMESHEET>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectGUID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> ExpectedCompletionDate { get; set; }
        public Nullable<System.DateTimeOffset> DueDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> ValidityID { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> ConfidentialityLevelID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<int> ImportanceID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUDIT> AUDIT { get; set; }
        public virtual CONFIDENTIALITYLEVEL CONFIDENTIALITYLEVEL { get; set; }
        public virtual CREATIONOBJECT CREATIONOBJECT { get; set; }
        public virtual IMPORTANCE IMPORTANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVESTIGATION> INVESTIGATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGANISATIONPROJECT> ORGANISATIONPROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONFORPROJECT> PERSONFORPROJECT { get; set; }
        public virtual PROJECT PROJECT1 { get; set; }
        public virtual PROJECT PROJECT2 { get; set; }
        public virtual VALIDITY VALIDITY { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTDESCRIPTION> PROJECTDESCRIPTION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTFINDING> PROJECTFINDING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTFORAPPLICATION> PROJECTFORAPPLICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTMAPPING> PROJECTMAPPING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTMAPPING> PROJECTMAPPING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTMETHODOLOGY> PROJECTMETHODOLOGY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTPERSON> PROJECTPERSON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTTAG> PROJECTTAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECTTASK> PROJECTTASK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYPROGRAMPROJECT> SECURITYPROGRAMPROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASKFORPROJECT> TASKFORPROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMESHEET> TIMESHEET { get; set; }
    }
}
