//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTTASKFINDING
    {
        public int ProjectTaskFindingID { get; set; }
        public Nullable<int> ProjectTaskID { get; set; }
        public string ProjectTaskGUID { get; set; }
        public Nullable<int> FindingID { get; set; }
        public string FindingGUID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual FINDING FINDING { get; set; }
        public virtual PROJECTTASK PROJECTTASK { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
