//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVIDERSFORACCOUNT
    {
        public int ProviderAccountID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntil { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual PROVIDER PROVIDER { get; set; }
    }
}
