//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAWARTIFACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RAWARTIFACT()
        {
            this.ARTIFACT = new HashSet<ARTIFACT>();
        }
    
        public int RawArtifactID { get; set; }
        public string RawArtifactGUID { get; set; }
        public string byte_order { get; set; }
        public Nullable<bool> is_encrypted { get; set; }
        public Nullable<bool> is_compressed { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> CollectionMethodID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> RepositoryID { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTIFACT> ARTIFACT { get; set; }
        public virtual COLLECTIONMETHOD COLLECTIONMETHOD { get; set; }
        public virtual CREATIONOBJECT CREATIONOBJECT { get; set; }
        public virtual REPOSITORY REPOSITORY { get; set; }
        public virtual SOURCE SOURCE { get; set; }
    }
}
