//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITYPROGRAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SECURITYPROGRAM()
        {
            this.SECURITYPROGRAMPROJECT = new HashSet<SECURITYPROGRAMPROJECT>();
        }
    
        public int SecurityProgramID { get; set; }
        public string SecurityProgramGUID { get; set; }
        public string SecurityProgramName { get; set; }
        public string SecurityProgramDescription { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<int> SecurityProgramTypeID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
    
        public virtual SECURITYPROGRAMTYPE SECURITYPROGRAMTYPE { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYPROGRAMPROJECT> SECURITYPROGRAMPROJECT { get; set; }
    }
}
