//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITYREQUIREMENTCONTROL
    {
        public int SecurityRequirementControlID { get; set; }
        public Nullable<int> SecurityRequirementID { get; set; }
        public string SecurityRequirementGUID { get; set; }
        public Nullable<int> SecurityControlID { get; set; }
        public string SecurityControlGUID { get; set; }
        public Nullable<int> EffectivenessID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual CREATIONOBJECT CREATIONOBJECT { get; set; }
        public virtual EFFECTIVENESS EFFECTIVENESS { get; set; }
        public virtual SECURITYCONTROL SECURITYCONTROL { get; set; }
        public virtual SECURITYREQUIREMENT SECURITYREQUIREMENT { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
