//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITYCONTROL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SECURITYCONTROL()
        {
            this.ASSETSECURITYCONTROL = new HashSet<ASSETSECURITYCONTROL>();
            this.CHANGECONTROL = new HashSet<CHANGECONTROL>();
            this.CHECKLISTQUESTIONSECURITYCONTROL = new HashSet<CHECKLISTQUESTIONSECURITYCONTROL>();
            this.COOKIESECURITYCONTROL = new HashSet<COOKIESECURITYCONTROL>();
            this.SECURITYCONTROL1 = new HashSet<SECURITYCONTROL>();
            this.SECURITYCONTROLFORHUMANRISK = new HashSet<SECURITYCONTROLFORHUMANRISK>();
            this.SECURITYCONTROLMAPPING = new HashSet<SECURITYCONTROLMAPPING>();
            this.SECURITYCONTROLMAPPING1 = new HashSet<SECURITYCONTROLMAPPING>();
            this.SECURITYCONTROLPRIORITY = new HashSet<SECURITYCONTROLPRIORITY>();
            this.SECURITYCONTROLREFERENCE = new HashSet<SECURITYCONTROLREFERENCE>();
            this.SECURITYCONTROLSTRENGTH = new HashSet<SECURITYCONTROLSTRENGTH>();
            this.SECURITYCONTROLTAG = new HashSet<SECURITYCONTROLTAG>();
            this.SECURITYCONTROLTEST = new HashSet<SECURITYCONTROLTEST>();
            this.SECURITYCONTROLTOOL = new HashSet<SECURITYCONTROLTOOL>();
            this.SECURITYREQUIREMENTCONTROL = new HashSet<SECURITYREQUIREMENTCONTROL>();
        }
    
        public int SecurityControlID { get; set; }
        public string SecurityControlGUID { get; set; }
        public Nullable<int> ControlID { get; set; }
        public string SecurityControlName { get; set; }
        public string SecurityControlAbbrevation { get; set; }
        public string SecurityControlDescription { get; set; }
        public string BaselineImpact { get; set; }
        public string StatementDescription { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public string SecurityControlVocabularyID { get; set; }
        public Nullable<int> SecurityControlFamilyID { get; set; }
        public Nullable<int> SecurityControlParentID { get; set; }
        public Nullable<int> SecurityControlTypeID { get; set; }
        public Nullable<int> RepositoryID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> TrustLevelID { get; set; }
        public Nullable<int> TrustReasonID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<int> ReliabilityID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETSECURITYCONTROL> ASSETSECURITYCONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHANGECONTROL> CHANGECONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKLISTQUESTIONSECURITYCONTROL> CHECKLISTQUESTIONSECURITYCONTROL { get; set; }
        public virtual CONTROL CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COOKIESECURITYCONTROL> COOKIESECURITYCONTROL { get; set; }
        public virtual CREATIONOBJECT CREATIONOBJECT { get; set; }
        public virtual RELIABILITY RELIABILITY { get; set; }
        public virtual REPOSITORY REPOSITORY { get; set; }
        public virtual SECURITYCONTROLFAMILY SECURITYCONTROLFAMILY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYCONTROL> SECURITYCONTROL1 { get; set; }
        public virtual SECURITYCONTROL SECURITYCONTROL2 { get; set; }
        public virtual SECURITYCONTROLTYPE SECURITYCONTROLTYPE { get; set; }
        public virtual TRUSTLEVEL TRUSTLEVEL { get; set; }
        public virtual TRUSTREASON TRUSTREASON { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYCONTROLFORHUMANRISK> SECURITYCONTROLFORHUMANRISK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYCONTROLMAPPING> SECURITYCONTROLMAPPING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYCONTROLMAPPING> SECURITYCONTROLMAPPING1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYCONTROLPRIORITY> SECURITYCONTROLPRIORITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYCONTROLREFERENCE> SECURITYCONTROLREFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYCONTROLSTRENGTH> SECURITYCONTROLSTRENGTH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYCONTROLTAG> SECURITYCONTROLTAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYCONTROLTEST> SECURITYCONTROLTEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYCONTROLTOOL> SECURITYCONTROLTOOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYREQUIREMENTCONTROL> SECURITYREQUIREMENTCONTROL { get; set; }
    }
}
