//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITYREQUIREMENTTEST
    {
        public int SecurityRequirementTestID { get; set; }
        public string SecurityRequirementTestGUID { get; set; }
        public Nullable<int> SecurityRequirementID { get; set; }
        public string SecurityRequirementGUID { get; set; }
        public Nullable<int> TestID { get; set; }
        public string TestGUID { get; set; }
        public Nullable<int> TestVocabularyID { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
    
        public virtual SECURITYREQUIREMENT SECURITYREQUIREMENT { get; set; }
        public virtual TEST TEST { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
