//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSIONCOOKIEATTRIBUTEVALUE
    {
        public int SessionCookieAttributeValueID { get; set; }
        public int SessionCookieID { get; set; }
        public string SessionCookieGUID { get; set; }
        public int AttributeValueID { get; set; }
        public string AttributeValueGUID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public string SessionCookieAttributeValueName { get; set; }
        public string SessionCookieAttributeValueDescription { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<int> VocabularyID { get; set; }
    
        public virtual ATTRIBUTEVALUE ATTRIBUTEVALUE { get; set; }
        public virtual SESSIONCOOKIE SESSIONCOOKIE { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
