//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUSPECTEDMALICIOUSREASON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUSPECTEDMALICIOUSREASON()
        {
            this.ACCESSEDDIRECTORYLIST = new HashSet<ACCESSEDDIRECTORYLIST>();
            this.ACCESSEDFILELIST = new HashSet<ACCESSEDFILELIST>();
            this.ACCESSRECORD = new HashSet<ACCESSRECORD>();
            this.ARPCACHEENTRIES = new HashSet<ARPCACHEENTRIES>();
            this.ARTIFACT = new HashSet<ARTIFACT>();
            this.CREATIONOBJECT = new HashSet<CREATIONOBJECT>();
            this.EMAILADDRESS = new HashSet<EMAILADDRESS>();
            this.EMAILHEADER = new HashSet<EMAILHEADER>();
            this.EMAILMESSAGE = new HashSet<EMAILMESSAGE>();
            this.EMAILMESSAGELINK = new HashSet<EMAILMESSAGELINK>();
            this.LINK = new HashSet<LINK>();
        }
    
        public int SuspectedMaliciousReasonID { get; set; }
        public string SuspectedMaliciousReasonGUID { get; set; }
        public string SuspectedMaliciousReasonName { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public string SuspectedMaliciousReasonDescription { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<int> VocabularyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCESSEDDIRECTORYLIST> ACCESSEDDIRECTORYLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCESSEDFILELIST> ACCESSEDFILELIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCESSRECORD> ACCESSRECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARPCACHEENTRIES> ARPCACHEENTRIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTIFACT> ARTIFACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CREATIONOBJECT> CREATIONOBJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILADDRESS> EMAILADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILHEADER> EMAILHEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILMESSAGE> EMAILMESSAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILMESSAGELINK> EMAILMESSAGELINK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LINK> LINK { get; set; }
        public virtual REASON REASON { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
