//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEMTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYSTEMTYPE()
        {
            this.SYSTEMTYPEFORASSET = new HashSet<SYSTEMTYPEFORASSET>();
            this.SYSTEMTYPEFORTHREATACTORTTP = new HashSet<SYSTEMTYPEFORTHREATACTORTTP>();
        }
    
        public int SystemTypeID { get; set; }
        public string SystemTypeGUID { get; set; }
        public string SystemTypeName { get; set; }
        public string SystemTypeDescription { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<int> EnumerationVersionID { get; set; }
    
        public virtual ENUMERATIONVERSION ENUMERATIONVERSION { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEMTYPEFORASSET> SYSTEMTYPEFORASSET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYSTEMTYPEFORTHREATACTORTTP> SYSTEMTYPEFORTHREATACTORTTP { get; set; }
    }
}
