//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAGTAG
    {
        public int TagTagID { get; set; }
        public string TagTagGUID { get; set; }
        public Nullable<int> TagParentID { get; set; }
        public string TagParentGUID { get; set; }
        public Nullable<int> TagSubjectID { get; set; }
        public string TagSubjectGUID { get; set; }
        public string TagRelationship { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> ConfidenceLevelID { get; set; }
        public Nullable<int> ConfidenceReasonID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<int> ImportanceID { get; set; }
    
        public virtual CONFIDENCELEVEL CONFIDENCELEVEL { get; set; }
        public virtual CONFIDENCEREASON CONFIDENCEREASON { get; set; }
        public virtual CREATIONOBJECT CREATIONOBJECT { get; set; }
        public virtual IMPORTANCE IMPORTANCE { get; set; }
        public virtual SOURCE SOURCE { get; set; }
        public virtual TAG TAG { get; set; }
        public virtual TAG TAG1 { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
