//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASKATTACHMENT
    {
        public int TaskAttachmentID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string Title { get; set; }
        public byte[] Data { get; set; }
        public string MimeType { get; set; }
    
        public virtual TASK TASK { get; set; }
    }
}
