//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTMECHANISMEFFICACY
    {
        public int TestMechanismEfficacyID { get; set; }
        public string Efficacy { get; set; }
        public string EfficacyDescription { get; set; }
        public string ConfidenceLevel { get; set; }
        public Nullable<int> ConfidenceLevelID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
    
        public virtual CONFIDENCELEVEL CONFIDENCELEVEL1 { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
    }
}
