//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIMESHEET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIMESHEET()
        {
            this.TIMESHEETPERSON = new HashSet<TIMESHEETPERSON>();
        }
    
        public int TimesheetID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public string TimesheetName { get; set; }
        public string TimesheetDescription { get; set; }
        public Nullable<double> TimeValue { get; set; }
        public Nullable<int> TimeUnitID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> ProjectTaskID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual PROJECT PROJECT { get; set; }
        public virtual PROJECTTASK PROJECTTASK { get; set; }
        public virtual TASK TASK { get; set; }
        public virtual TIMEUNIT TIMEUNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIMESHEETPERSON> TIMESHEETPERSON { get; set; }
    }
}
