//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOLREFERENCE
    {
        public int ToolReferenceID { get; set; }
        public int ToolID { get; set; }
        public int ReferenceID { get; set; }
        public Nullable<int> ToolReferenceTypeID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> ConfidenceLevelID { get; set; }
        public Nullable<int> CollectionMethodID { get; set; }
        public Nullable<int> TrustLevelID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<int> ConfidentialityLevelID { get; set; }
    
        public virtual COLLECTIONMETHOD COLLECTIONMETHOD { get; set; }
        public virtual CONFIDENCELEVEL CONFIDENCELEVEL { get; set; }
        public virtual CONFIDENTIALITYLEVEL CONFIDENTIALITYLEVEL { get; set; }
        public virtual REFERENCE REFERENCE { get; set; }
        public virtual TOOL TOOL { get; set; }
        public virtual TOOLREFERENCETYPE TOOLREFERENCETYPE { get; set; }
        public virtual TRUSTLEVEL TRUSTLEVEL { get; set; }
    }
}
