//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOOL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOOL()
        {
            this.ARTIFACTPACKAGING = new HashSet<ARTIFACTPACKAGING>();
            this.ASSETDEVICE = new HashSet<ASSETDEVICE>();
            this.ASSETGEOLOCATION = new HashSet<ASSETGEOLOCATION>();
            this.CODELANGUAGES = new HashSet<CODELANGUAGES>();
            this.CODELANGUAGES1 = new HashSet<CODELANGUAGES>();
            this.COOKIE = new HashSet<COOKIE>();
            this.CPEFORTOOL = new HashSet<CPEFORTOOL>();
            this.CREATIONOBJECT = new HashSet<CREATIONOBJECT>();
            this.DEFENSETOOL = new HashSet<DEFENSETOOL>();
            this.DOMAINORGANISATION = new HashSet<DOMAINORGANISATION>();
            this.EXPLOITOSINSTRUCTIONMEMORYADDRESS = new HashSet<EXPLOITOSINSTRUCTIONMEMORYADDRESS>();
            this.FIREWALLRULE = new HashSet<FIREWALLRULE>();
            this.FIREWALLRULE1 = new HashSet<FIREWALLRULE>();
            this.HASHLIST = new HashSet<HASHLIST>();
            this.HASHVALUE = new HashSet<HASHVALUE>();
            this.HTTPCLIENTREQUEST = new HashSet<HTTPCLIENTREQUEST>();
            this.HTTPMESSAGE = new HashSet<HTTPMESSAGE>();
            this.HTTPMESSAGE1 = new HashSet<HTTPMESSAGE>();
            this.HTTPREQUESTHEADER = new HashSet<HTTPREQUESTHEADER>();
            this.HTTPREQUESTHEADERFIELDS = new HashSet<HTTPREQUESTHEADERFIELDS>();
            this.HTTPREQUESTRESPONSE = new HashSet<HTTPREQUESTRESPONSE>();
            this.HTTPRESPONSEHEADER = new HashSet<HTTPRESPONSEHEADER>();
            this.HTTPRESPONSEHEADERFIELDS = new HashSet<HTTPRESPONSEHEADERFIELDS>();
            this.HTTPSERVERRESPONSE = new HashSet<HTTPSERVERRESPONSE>();
            this.IDTENTRY = new HashSet<IDTENTRY>();
            this.IDTENTRYLISTENTRIES = new HashSet<IDTENTRYLISTENTRIES>();
            this.MEMORYADDRESS = new HashSet<MEMORYADDRESS>();
            this.PACKAGINGCOMPRESSION = new HashSet<PACKAGINGCOMPRESSION>();
            this.PACKAGINGENCODING = new HashSet<PACKAGINGENCODING>();
            this.PACKAGINGENCRYPTION = new HashSet<PACKAGINGENCRYPTION>();
            this.TOOLCODE = new HashSet<TOOLCODE>();
            this.TOOLFUNCTION = new HashSet<TOOLFUNCTION>();
            this.TOOLINFORMATIONFORTOOL = new HashSet<TOOLINFORMATIONFORTOOL>();
            this.TOOLLICENSE = new HashSet<TOOLLICENSE>();
            this.TOOLREFERENCE = new HashSet<TOOLREFERENCE>();
            this.TOOLTAG = new HashSet<TOOLTAG>();
            this.TOOLUSERAGENT = new HashSet<TOOLUSERAGENT>();
            this.WORDLISTWORDS = new HashSet<WORDLISTWORDS>();
            this.TOOLCOMPENSATIONMODEL = new HashSet<TOOLCOMPENSATIONMODEL>();
        }
    
        public int ToolID { get; set; }
        public string ToolGUID { get; set; }
        public string ToolName { get; set; }
        public string ToolDescription { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<int> ConfidenceLevelID { get; set; }
        public Nullable<int> TrustLevelID { get; set; }
        public Nullable<int> ReliabilityID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTIFACTPACKAGING> ARTIFACTPACKAGING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETDEVICE> ASSETDEVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETGEOLOCATION> ASSETGEOLOCATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CODELANGUAGES> CODELANGUAGES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CODELANGUAGES> CODELANGUAGES1 { get; set; }
        public virtual CONFIDENCELEVEL CONFIDENCELEVEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COOKIE> COOKIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPEFORTOOL> CPEFORTOOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CREATIONOBJECT> CREATIONOBJECT { get; set; }
        public virtual CREATIONOBJECT CREATIONOBJECT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEFENSETOOL> DEFENSETOOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOMAINORGANISATION> DOMAINORGANISATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXPLOITOSINSTRUCTIONMEMORYADDRESS> EXPLOITOSINSTRUCTIONMEMORYADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIREWALLRULE> FIREWALLRULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIREWALLRULE> FIREWALLRULE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HASHLIST> HASHLIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HASHVALUE> HASHVALUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTTPCLIENTREQUEST> HTTPCLIENTREQUEST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTTPMESSAGE> HTTPMESSAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTTPMESSAGE> HTTPMESSAGE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTTPREQUESTHEADER> HTTPREQUESTHEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTTPREQUESTHEADERFIELDS> HTTPREQUESTHEADERFIELDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTTPREQUESTRESPONSE> HTTPREQUESTRESPONSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTTPRESPONSEHEADER> HTTPRESPONSEHEADER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTTPRESPONSEHEADERFIELDS> HTTPRESPONSEHEADERFIELDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HTTPSERVERRESPONSE> HTTPSERVERRESPONSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDTENTRY> IDTENTRY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDTENTRYLISTENTRIES> IDTENTRYLISTENTRIES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEMORYADDRESS> MEMORYADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKAGINGCOMPRESSION> PACKAGINGCOMPRESSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKAGINGENCODING> PACKAGINGENCODING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACKAGINGENCRYPTION> PACKAGINGENCRYPTION { get; set; }
        public virtual RELIABILITY RELIABILITY { get; set; }
        public virtual TRUSTLEVEL TRUSTLEVEL { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLCODE> TOOLCODE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLFUNCTION> TOOLFUNCTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLINFORMATIONFORTOOL> TOOLINFORMATIONFORTOOL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLLICENSE> TOOLLICENSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLREFERENCE> TOOLREFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLTAG> TOOLTAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLUSERAGENT> TOOLUSERAGENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WORDLISTWORDS> WORDLISTWORDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOOLCOMPENSATIONMODEL> TOOLCOMPENSATIONMODEL { get; set; }
    }
}
