//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        public int TransactionID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Status { get; set; }
        public string OrderNumber { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string ProductID { get; set; }
        public string ProductDescription { get; set; }
        public string HolderName { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual aspnet_Membership aspnet_Membership { get; set; }
    }
}
