//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALIDITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VALIDITY()
        {
            this.ACCOUNT = new HashSet<ACCOUNT>();
            this.ACCOUNTAUTHENTICATIONTYPE = new HashSet<ACCOUNTAUTHENTICATIONTYPE>();
            this.ACRONYM = new HashSet<ACRONYM>();
            this.APPLICATIONURIWHITELIST = new HashSet<APPLICATIONURIWHITELIST>();
            this.ASSETCERTIFICATE = new HashSet<ASSETCERTIFICATE>();
            this.ASSETCRITICALITYLEVEL = new HashSet<ASSETCRITICALITYLEVEL>();
            this.ASSETCRITICALITYLEVELFORASSET = new HashSet<ASSETCRITICALITYLEVELFORASSET>();
            this.ASSETNETWORKZONE = new HashSet<ASSETNETWORKZONE>();
            this.ASSETNETWORKZONERESTRICTION = new HashSet<ASSETNETWORKZONERESTRICTION>();
            this.ASSETSECURITYCONTROL = new HashSet<ASSETSECURITYCONTROL>();
            this.AUTHENTICATIONTYPE = new HashSet<AUTHENTICATIONTYPE>();
            this.CATEGORY = new HashSet<CATEGORY>();
            this.CERTIFICATION = new HashSet<CERTIFICATION>();
            this.CLASSIFICATIONRESTRICTION = new HashSet<CLASSIFICATIONRESTRICTION>();
            this.CONNECTIONFORASSET = new HashSet<CONNECTIONFORASSET>();
            this.CONTROL = new HashSet<CONTROL>();
            this.CONTROLCATEGORY = new HashSet<CONTROLCATEGORY>();
            this.CPETAG = new HashSet<CPETAG>();
            this.CREDENTIAL = new HashSet<CREDENTIAL>();
            this.EMAILMESSAGE = new HashSet<EMAILMESSAGE>();
            this.EMAILMESSAGERESTRICTION = new HashSet<EMAILMESSAGERESTRICTION>();
            this.EMAILRECIPIENTS = new HashSet<EMAILRECIPIENTS>();
            this.FILE = new HashSet<FILE>();
            this.FILEDESCRIPTION = new HashSet<FILEDESCRIPTION>();
            this.FILEEXTENSION = new HashSet<FILEEXTENSION>();
            this.FILELIST = new HashSet<FILELIST>();
            this.FILELISTFILES = new HashSet<FILELISTFILES>();
            this.FILEREPOSITORY = new HashSet<FILEREPOSITORY>();
            this.FINDINGCATEGORY = new HashSet<FINDINGCATEGORY>();
            this.FINDINGREFERENCE = new HashSet<FINDINGREFERENCE>();
            this.FINDINGTAG = new HashSet<FINDINGTAG>();
            this.FIREWALLRULE = new HashSet<FIREWALLRULE>();
            this.LANGUAGEFUNCTION = new HashSet<LANGUAGEFUNCTION>();
            this.METHODOLOGY = new HashSet<METHODOLOGY>();
            this.METHODOLOGYDESCRIPTION = new HashSet<METHODOLOGYDESCRIPTION>();
            this.NETWORKZONE = new HashSet<NETWORKZONE>();
            this.ORGANIZATIONALUNIT = new HashSet<ORGANIZATIONALUNIT>();
            this.PERSONFORORGANISATION = new HashSet<PERSONFORORGANISATION>();
            this.PHYSICALLOCATIONTAG = new HashSet<PHYSICALLOCATIONTAG>();
            this.PLUGINREFERENCE = new HashSet<PLUGINREFERENCE>();
            this.PLUGINVERSION = new HashSet<PLUGINVERSION>();
            this.PROJECT = new HashSet<PROJECT>();
            this.PROVIDER = new HashSet<PROVIDER>();
            this.REFERENCE = new HashSet<REFERENCE>();
            this.REPOSITORY = new HashSet<REPOSITORY>();
            this.SECURITYDOMAINMATURITY = new HashSet<SECURITYDOMAINMATURITY>();
            this.STAGE = new HashSet<STAGE>();
            this.STAGEDESCRIPTION = new HashSet<STAGEDESCRIPTION>();
            this.STRUCTUREDAUTHENTICATIONMECHANISM = new HashSet<STRUCTUREDAUTHENTICATIONMECHANISM>();
            this.TAG = new HashSet<TAG>();
            this.TASK = new HashSet<TASK>();
            this.TECHNIQUE = new HashSet<TECHNIQUE>();
            this.TECHNIQUEREFERENCETAG = new HashSet<TECHNIQUEREFERENCETAG>();
            this.TELEPHONE = new HashSet<TELEPHONE>();
            this.TIP = new HashSet<TIP>();
            this.VOCABULARYTAG = new HashSet<VOCABULARYTAG>();
            this.X509CERTIFICATE = new HashSet<X509CERTIFICATE>();
            this.X509V3EXTENSION = new HashSet<X509V3EXTENSION>();
            this.ZONE = new HashSet<ZONE>();
        }
    
        public int ValidityID { get; set; }
        public Nullable<System.DateTimeOffset> Not_Before { get; set; }
        public Nullable<System.DateTimeOffset> Not_After { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT> ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNTAUTHENTICATIONTYPE> ACCOUNTAUTHENTICATIONTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACRONYM> ACRONYM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICATIONURIWHITELIST> APPLICATIONURIWHITELIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETCERTIFICATE> ASSETCERTIFICATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETCRITICALITYLEVEL> ASSETCRITICALITYLEVEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETCRITICALITYLEVELFORASSET> ASSETCRITICALITYLEVELFORASSET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETNETWORKZONE> ASSETNETWORKZONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETNETWORKZONERESTRICTION> ASSETNETWORKZONERESTRICTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASSETSECURITYCONTROL> ASSETSECURITYCONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AUTHENTICATIONTYPE> AUTHENTICATIONTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORY> CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CERTIFICATION> CERTIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLASSIFICATIONRESTRICTION> CLASSIFICATIONRESTRICTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONNECTIONFORASSET> CONNECTIONFORASSET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROL> CONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTROLCATEGORY> CONTROLCATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CPETAG> CPETAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CREDENTIAL> CREDENTIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILMESSAGE> EMAILMESSAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILMESSAGERESTRICTION> EMAILMESSAGERESTRICTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMAILRECIPIENTS> EMAILRECIPIENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILE> FILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILEDESCRIPTION> FILEDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILEEXTENSION> FILEEXTENSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILELIST> FILELIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILELISTFILES> FILELISTFILES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILEREPOSITORY> FILEREPOSITORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINDINGCATEGORY> FINDINGCATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINDINGREFERENCE> FINDINGREFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FINDINGTAG> FINDINGTAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIREWALLRULE> FIREWALLRULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LANGUAGEFUNCTION> LANGUAGEFUNCTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<METHODOLOGY> METHODOLOGY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<METHODOLOGYDESCRIPTION> METHODOLOGYDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NETWORKZONE> NETWORKZONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGANIZATIONALUNIT> ORGANIZATIONALUNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PERSONFORORGANISATION> PERSONFORORGANISATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHYSICALLOCATIONTAG> PHYSICALLOCATIONTAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLUGINREFERENCE> PLUGINREFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLUGINVERSION> PLUGINVERSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT> PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVIDER> PROVIDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REFERENCE> REFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPOSITORY> REPOSITORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECURITYDOMAINMATURITY> SECURITYDOMAINMATURITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAGE> STAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STAGEDESCRIPTION> STAGEDESCRIPTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STRUCTUREDAUTHENTICATIONMECHANISM> STRUCTUREDAUTHENTICATIONMECHANISM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAG> TAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TASK> TASK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TECHNIQUE> TECHNIQUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TECHNIQUEREFERENCETAG> TECHNIQUEREFERENCETAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TELEPHONE> TELEPHONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIP> TIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VOCABULARYTAG> VOCABULARYTAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<X509CERTIFICATE> X509CERTIFICATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<X509V3EXTENSION> X509V3EXTENSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZONE> ZONE { get; set; }
    }
}
