//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XORCISMModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VULNERABLECONFIGURATIONCPE
    {
        public int VulnerableConfigurationCPEID { get; set; }
        public Nullable<int> VulnerableConfigurationID { get; set; }
        public Nullable<int> LogicalTestLevel { get; set; }
        public Nullable<int> LogicalTestLevelOrder { get; set; }
        public Nullable<int> CPELogicalTestID { get; set; }
        public Nullable<int> CPEID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual CPE CPE { get; set; }
        public virtual CPELOGICALTEST CPELOGICALTEST { get; set; }
        public virtual VOCABULARY VOCABULARY { get; set; }
        public virtual VULNERABLECONFIGURATION VULNERABLECONFIGURATION { get; set; }
    }
}
