//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XWINDOWSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WINDOWSSYSTEMRESTORE
    {
        public int WindowsSystemRestoreID { get; set; }
        public string Restore_Point_Description { get; set; }
        public string Restore_Point_Full_Path { get; set; }
        public string Restore_Point_Name { get; set; }
        public string Restore_Point_Type { get; set; }
        public string ACL_Change_SID { get; set; }
        public string ACL_Change_Username { get; set; }
        public string Backup_File_Name { get; set; }
        public string Change_Event { get; set; }
        public string ChangeLog_Entry_Flags { get; set; }
        public Nullable<int> ChangeLog_Entry_Sequence_Number { get; set; }
        public string ChangeLog_Entry_Type { get; set; }
        public string Change_Log_File_Name { get; set; }
        public Nullable<System.DateTimeOffset> Created { get; set; }
        public string File_Attributes { get; set; }
        public string New_File_Name { get; set; }
        public string Original_File_Name { get; set; }
        public string Original_Short_File_Name { get; set; }
        public string Process_Name { get; set; }
        public Nullable<int> Registry_Hive_List { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    }
}
