//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XWINDOWSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WINDOWSPREFETCHOBJECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WINDOWSPREFETCHOBJECT()
        {
            this.WINDOWSPREFETCHACCESSEDFILELIST = new HashSet<WINDOWSPREFETCHACCESSEDFILELIST>();
        }
    
        public int WindowsPrefetchObjectID { get; set; }
        public string Application_File_Name { get; set; }
        public Nullable<int> FileID { get; set; }
        public string CPEName { get; set; }
        public string Prefetch_Hash { get; set; }
        public Nullable<long> Times_Executed { get; set; }
        public Nullable<System.DateTimeOffset> First_Run { get; set; }
        public Nullable<System.DateTimeOffset> Last_Run { get; set; }
        public Nullable<int> VolumeObjectID { get; set; }
        public Nullable<int> WindowsVolumeID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WINDOWSPREFETCHACCESSEDFILELIST> WINDOWSPREFETCHACCESSEDFILELIST { get; set; }
    }
}
