//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XWINDOWSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WINDOWSTASK
    {
        public int WindowsTaskID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> SessionCronID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> TaskStatusID { get; set; }
        public string Priority { get; set; }
        public Nullable<int> TaskPriorityID { get; set; }
        public string Name { get; set; }
        public string Application_Name { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public string CPEName { get; set; }
        public string Parameters { get; set; }
        public string Flags { get; set; }
        public string Account_Name { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string Account_Run_Level { get; set; }
        public string Account_Logon_Type { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTimeOffset> Creation_Date { get; set; }
        public Nullable<System.DateTimeOffset> Most_Recent_Run_Time { get; set; }
        public Nullable<int> Exit_Code { get; set; }
        public Nullable<int> Max_Run_Time { get; set; }
        public Nullable<System.DateTimeOffset> Next_Run_Time { get; set; }
        public string Comment { get; set; }
        public string Working_Directory { get; set; }
        public Nullable<int> DirectoryID { get; set; }
        public string Work_Item_Data { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    }
}
