//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XATTACKModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACKPATTERN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATTACKPATTERN()
        {
            this.ATTACKPATTERNATTACKCONSEQUENCE = new HashSet<ATTACKPATTERNATTACKCONSEQUENCE>();
            this.ATTACKPATTERNCWE = new HashSet<ATTACKPATTERNCWE>();
            this.ATTACKPATTERNFORTHREATACTORTTP = new HashSet<ATTACKPATTERNFORTHREATACTORTTP>();
            this.ATTACKPATTERNINDICATORWARNING = new HashSet<ATTACKPATTERNINDICATORWARNING>();
            this.ATTACKPATTERNMITIGATION = new HashSet<ATTACKPATTERNMITIGATION>();
            this.ATTACKPATTERNNOTES = new HashSet<ATTACKPATTERNNOTES>();
            this.ATTACKPATTERNOBFUSCATIONTECHNIQUE = new HashSet<ATTACKPATTERNOBFUSCATIONTECHNIQUE>();
            this.ATTACKPATTERNPROBINGTECHNIQUE = new HashSet<ATTACKPATTERNPROBINGTECHNIQUE>();
            this.ATTACKPATTERNREFERENCE = new HashSet<ATTACKPATTERNREFERENCE>();
            this.ATTACKPATTERNRELATIONSHIP = new HashSet<ATTACKPATTERNRELATIONSHIP>();
            this.ATTACKPATTERNRELATIONSHIP1 = new HashSet<ATTACKPATTERNRELATIONSHIP>();
            this.ATTACKPATTERNSECURITYCONTROL = new HashSet<ATTACKPATTERNSECURITYCONTROL>();
            this.ATTACKPATTERNTAG = new HashSet<ATTACKPATTERNTAG>();
            this.ATTACKPATTERNVIEWRELATIONSHIP = new HashSet<ATTACKPATTERNVIEWRELATIONSHIP>();
            this.ATTACKPAYLOADFORATTACKPATTERN = new HashSet<ATTACKPAYLOADFORATTACKPATTERN>();
            this.ATTACKPAYLOADIMPACTFORATTACKPATTERN = new HashSet<ATTACKPAYLOADIMPACTFORATTACKPATTERN>();
            this.ATTACKPHASEFORATTACKPATTERN = new HashSet<ATTACKPHASEFORATTACKPATTERN>();
            this.ATTACKPREREQUISITEFORATTACKPATTERN = new HashSet<ATTACKPREREQUISITEFORATTACKPATTERN>();
            this.ATTACKPURPOSEFORATTACKPATTERN = new HashSet<ATTACKPURPOSEFORATTACKPATTERN>();
            this.ATTACKRESOURCEFORATTACKPATTERN = new HashSet<ATTACKRESOURCEFORATTACKPATTERN>();
            this.ATTACKSTEPTECHNIQUELEVERAGEDPATTERN = new HashSet<ATTACKSTEPTECHNIQUELEVERAGEDPATTERN>();
            this.ATTACKSURFACEFORATTACKPATTERN = new HashSet<ATTACKSURFACEFORATTACKPATTERN>();
        }
    
        public int AttackPatternID { get; set; }
        public string AttackPatternGUID { get; set; }
        public string capec_id { get; set; }
        public Nullable<bool> category { get; set; }
        public string AttackPatternName { get; set; }
        public string AttackPatternDescription { get; set; }
        public string PatternAbstraction { get; set; }
        public string PatternCompleteness { get; set; }
        public string PatternStatus { get; set; }
        public string TypicalSeverity { get; set; }
        public string Payload_Activation_Impact { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string SourceGUID { get; set; }
        public Nullable<int> RepositoryID { get; set; }
        public string RepositoryGUID { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public string VocabularyGUID { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public string CreationObjectGUID { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPATTERNATTACKCONSEQUENCE> ATTACKPATTERNATTACKCONSEQUENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPATTERNCWE> ATTACKPATTERNCWE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPATTERNFORTHREATACTORTTP> ATTACKPATTERNFORTHREATACTORTTP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPATTERNINDICATORWARNING> ATTACKPATTERNINDICATORWARNING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPATTERNMITIGATION> ATTACKPATTERNMITIGATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPATTERNNOTES> ATTACKPATTERNNOTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPATTERNOBFUSCATIONTECHNIQUE> ATTACKPATTERNOBFUSCATIONTECHNIQUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPATTERNPROBINGTECHNIQUE> ATTACKPATTERNPROBINGTECHNIQUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPATTERNREFERENCE> ATTACKPATTERNREFERENCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPATTERNRELATIONSHIP> ATTACKPATTERNRELATIONSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPATTERNRELATIONSHIP> ATTACKPATTERNRELATIONSHIP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPATTERNSECURITYCONTROL> ATTACKPATTERNSECURITYCONTROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPATTERNTAG> ATTACKPATTERNTAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPATTERNVIEWRELATIONSHIP> ATTACKPATTERNVIEWRELATIONSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPAYLOADFORATTACKPATTERN> ATTACKPAYLOADFORATTACKPATTERN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPAYLOADIMPACTFORATTACKPATTERN> ATTACKPAYLOADIMPACTFORATTACKPATTERN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPHASEFORATTACKPATTERN> ATTACKPHASEFORATTACKPATTERN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPREREQUISITEFORATTACKPATTERN> ATTACKPREREQUISITEFORATTACKPATTERN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKPURPOSEFORATTACKPATTERN> ATTACKPURPOSEFORATTACKPATTERN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKRESOURCEFORATTACKPATTERN> ATTACKRESOURCEFORATTACKPATTERN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKSTEPTECHNIQUELEVERAGEDPATTERN> ATTACKSTEPTECHNIQUELEVERAGEDPATTERN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTACKSURFACEFORATTACKPATTERN> ATTACKSURFACEFORATTACKPATTERN { get; set; }
    }
}
