//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XATTACKModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTACKPATTERNINDICATORWARNING
    {
        public int AttackPatternIndicatorWarningID { get; set; }
        public Nullable<int> AttackPatternID { get; set; }
        public Nullable<int> AttackPatternIndicatorWarningOrder { get; set; }
        public string IndicatorWarningAttack { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        public virtual ATTACKPATTERN ATTACKPATTERN { get; set; }
    }
}
