//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XATTACKModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XATTACKEntities : DbContext
    {
        public XATTACKEntities()
            : base("name=XATTACKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATTACKCATEGORY> ATTACKCATEGORY { get; set; }
        public virtual DbSet<ATTACKCATEGORYREFERENCE> ATTACKCATEGORYREFERENCE { get; set; }
        public virtual DbSet<ATTACKCONSEQUENCE> ATTACKCONSEQUENCE { get; set; }
        public virtual DbSet<ATTACKCONSEQUENCETAG> ATTACKCONSEQUENCETAG { get; set; }
        public virtual DbSet<ATTACKEXAMPLE> ATTACKEXAMPLE { get; set; }
        public virtual DbSet<ATTACKEXAMPLEFORATTACKPATTERN> ATTACKEXAMPLEFORATTACKPATTERN { get; set; }
        public virtual DbSet<ATTACKEXECUTIONFLOW> ATTACKEXECUTIONFLOW { get; set; }
        public virtual DbSet<ATTACKEXECUTIONFLOWPHASE> ATTACKEXECUTIONFLOWPHASE { get; set; }
        public virtual DbSet<ATTACKMETHOD> ATTACKMETHOD { get; set; }
        public virtual DbSet<ATTACKMETHODDESCRIPTION> ATTACKMETHODDESCRIPTION { get; set; }
        public virtual DbSet<ATTACKMETHODFORATTACKPATTERN> ATTACKMETHODFORATTACKPATTERN { get; set; }
        public virtual DbSet<ATTACKMETHODREFERENCE> ATTACKMETHODREFERENCE { get; set; }
        public virtual DbSet<ATTACKMETHODTAG> ATTACKMETHODTAG { get; set; }
        public virtual DbSet<ATTACKPATTERN> ATTACKPATTERN { get; set; }
        public virtual DbSet<ATTACKPATTERNATTACKCONSEQUENCE> ATTACKPATTERNATTACKCONSEQUENCE { get; set; }
        public virtual DbSet<ATTACKPATTERNATTACKCONSEQUENCESCOPE> ATTACKPATTERNATTACKCONSEQUENCESCOPE { get; set; }
        public virtual DbSet<ATTACKPATTERNATTACKTECHNICALIMPACT> ATTACKPATTERNATTACKTECHNICALIMPACT { get; set; }
        public virtual DbSet<ATTACKPATTERNCWE> ATTACKPATTERNCWE { get; set; }
        public virtual DbSet<ATTACKPATTERNFORTHREATACTORTTP> ATTACKPATTERNFORTHREATACTORTTP { get; set; }
        public virtual DbSet<ATTACKPATTERNINDICATORWARNING> ATTACKPATTERNINDICATORWARNING { get; set; }
        public virtual DbSet<ATTACKPATTERNMITIGATION> ATTACKPATTERNMITIGATION { get; set; }
        public virtual DbSet<ATTACKPATTERNNOTE> ATTACKPATTERNNOTE { get; set; }
        public virtual DbSet<ATTACKPATTERNNOTES> ATTACKPATTERNNOTES { get; set; }
        public virtual DbSet<ATTACKPATTERNOBFUSCATIONTECHNIQUE> ATTACKPATTERNOBFUSCATIONTECHNIQUE { get; set; }
        public virtual DbSet<ATTACKPATTERNPROBINGTECHNIQUE> ATTACKPATTERNPROBINGTECHNIQUE { get; set; }
        public virtual DbSet<ATTACKPATTERNREFERENCE> ATTACKPATTERNREFERENCE { get; set; }
        public virtual DbSet<ATTACKPATTERNRELATIONSHIP> ATTACKPATTERNRELATIONSHIP { get; set; }
        public virtual DbSet<ATTACKPATTERNSECURITYCONTROL> ATTACKPATTERNSECURITYCONTROL { get; set; }
        public virtual DbSet<ATTACKPATTERNTAG> ATTACKPATTERNTAG { get; set; }
        public virtual DbSet<ATTACKPATTERNVIEW> ATTACKPATTERNVIEW { get; set; }
        public virtual DbSet<ATTACKPATTERNVIEWRELATIONSHIP> ATTACKPATTERNVIEWRELATIONSHIP { get; set; }
        public virtual DbSet<ATTACKPAYLOAD> ATTACKPAYLOAD { get; set; }
        public virtual DbSet<ATTACKPAYLOADENCODER> ATTACKPAYLOADENCODER { get; set; }
        public virtual DbSet<ATTACKPAYLOADFORATTACKPATTERN> ATTACKPAYLOADFORATTACKPATTERN { get; set; }
        public virtual DbSet<ATTACKPAYLOADIMPACT> ATTACKPAYLOADIMPACT { get; set; }
        public virtual DbSet<ATTACKPAYLOADIMPACTFORATTACKPATTERN> ATTACKPAYLOADIMPACTFORATTACKPATTERN { get; set; }
        public virtual DbSet<ATTACKPHASE> ATTACKPHASE { get; set; }
        public virtual DbSet<ATTACKPHASEFORATTACKPATTERN> ATTACKPHASEFORATTACKPATTERN { get; set; }
        public virtual DbSet<ATTACKPREREQUISITE> ATTACKPREREQUISITE { get; set; }
        public virtual DbSet<ATTACKPREREQUISITEFORATTACKPATTERN> ATTACKPREREQUISITEFORATTACKPATTERN { get; set; }
        public virtual DbSet<ATTACKPURPOSE> ATTACKPURPOSE { get; set; }
        public virtual DbSet<ATTACKPURPOSEFORATTACKPATTERN> ATTACKPURPOSEFORATTACKPATTERN { get; set; }
        public virtual DbSet<ATTACKRESOURCE> ATTACKRESOURCE { get; set; }
        public virtual DbSet<ATTACKRESOURCEFORATTACKPATTERN> ATTACKRESOURCEFORATTACKPATTERN { get; set; }
        public virtual DbSet<ATTACKRESOURCETAG> ATTACKRESOURCETAG { get; set; }
        public virtual DbSet<ATTACKSCENARIO> ATTACKSCENARIO { get; set; }
        public virtual DbSet<ATTACKSCOPE> ATTACKSCOPE { get; set; }
        public virtual DbSet<ATTACKSTEP> ATTACKSTEP { get; set; }
        public virtual DbSet<ATTACKSTEPINDICATOR> ATTACKSTEPINDICATOR { get; set; }
        public virtual DbSet<ATTACKSTEPINDICATORENVIRONMENT> ATTACKSTEPINDICATORENVIRONMENT { get; set; }
        public virtual DbSet<ATTACKSTEPINDICATORTAG> ATTACKSTEPINDICATORTAG { get; set; }
        public virtual DbSet<ATTACKSTEPOUTCOME> ATTACKSTEPOUTCOME { get; set; }
        public virtual DbSet<ATTACKSTEPOUTCOMETAG> ATTACKSTEPOUTCOMETAG { get; set; }
        public virtual DbSet<ATTACKSTEPSECURITYCONTROL> ATTACKSTEPSECURITYCONTROL { get; set; }
        public virtual DbSet<ATTACKSTEPTAG> ATTACKSTEPTAG { get; set; }
        public virtual DbSet<ATTACKSTEPTECHNIQUE> ATTACKSTEPTECHNIQUE { get; set; }
        public virtual DbSet<ATTACKSTEPTECHNIQUEENVIRONMENT> ATTACKSTEPTECHNIQUEENVIRONMENT { get; set; }
        public virtual DbSet<ATTACKSTEPTECHNIQUELEVERAGEDPATTERN> ATTACKSTEPTECHNIQUELEVERAGEDPATTERN { get; set; }
        public virtual DbSet<ATTACKSURFACE> ATTACKSURFACE { get; set; }
        public virtual DbSet<ATTACKSURFACECHANGERECORD> ATTACKSURFACECHANGERECORD { get; set; }
        public virtual DbSet<ATTACKSURFACEFORATTACKPATTERN> ATTACKSURFACEFORATTACKPATTERN { get; set; }
        public virtual DbSet<ATTACKSURFACEINTERACTIONPOINTS> ATTACKSURFACEINTERACTIONPOINTS { get; set; }
        public virtual DbSet<ATTACKSURFACELOCALITY> ATTACKSURFACELOCALITY { get; set; }
        public virtual DbSet<ATTACKSURFACELOCALITYFORATTACKSURFACE> ATTACKSURFACELOCALITYFORATTACKSURFACE { get; set; }
        public virtual DbSet<ATTACKSURFACESERVICE> ATTACKSURFACESERVICE { get; set; }
        public virtual DbSet<ATTACKSURFACESERVICEPROTOCOL> ATTACKSURFACESERVICEPROTOCOL { get; set; }
        public virtual DbSet<ATTACKSURFACETYPE> ATTACKSURFACETYPE { get; set; }
        public virtual DbSet<ATTACKSURFACETYPEFORATTACKSURFACE> ATTACKSURFACETYPEFORATTACKSURFACE { get; set; }
        public virtual DbSet<ATTACKTECHNICALIMPACT> ATTACKTECHNICALIMPACT { get; set; }
        public virtual DbSet<ATTACKTECHNIQUE> ATTACKTECHNIQUE { get; set; }
        public virtual DbSet<ATTACKTECHNIQUEINDICATOR> ATTACKTECHNIQUEINDICATOR { get; set; }
        public virtual DbSet<ATTACKTECHNIQUEREFERENCE> ATTACKTECHNIQUEREFERENCE { get; set; }
        public virtual DbSet<ATTACKTECHNIQUETAG> ATTACKTECHNIQUETAG { get; set; }
        public virtual DbSet<ATTACKTECHNIQUETOOL> ATTACKTECHNIQUETOOL { get; set; }
        public virtual DbSet<ATTACKTOOL> ATTACKTOOL { get; set; }
        public virtual DbSet<ATTACKTOOLAUTHENTICATIONTYPE> ATTACKTOOLAUTHENTICATIONTYPE { get; set; }
        public virtual DbSet<ATTACKTOOLDESCRIPTION> ATTACKTOOLDESCRIPTION { get; set; }
        public virtual DbSet<ATTACKTOOLFORTHREATACTORTTP> ATTACKTOOLFORTHREATACTORTTP { get; set; }
        public virtual DbSet<ATTACKTOOLMODULE> ATTACKTOOLMODULE { get; set; }
        public virtual DbSet<ATTACKTOOLMODULEAUTHENTICATIONTYPE> ATTACKTOOLMODULEAUTHENTICATIONTYPE { get; set; }
        public virtual DbSet<ATTACKTOOLTAG> ATTACKTOOLTAG { get; set; }
        public virtual DbSet<ATTACKTOOLTYPE> ATTACKTOOLTYPE { get; set; }
        public virtual DbSet<ATTACKVECTOR> ATTACKVECTOR { get; set; }
    }
}
