//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTHREATModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class THREATCAMPAIGNFORTHREATCAMPAIGN
    {
        public int ThreatCampaignMappingID { get; set; }
        public int ThreatCampaignRefID { get; set; }
        public string ThreatCampaignRefGUID { get; set; }
        public string Relationship { get; set; }
        public int ThreatCampaignSubjectID { get; set; }
        public string ThreatCampaignSubjectGUID { get; set; }
        public System.DateTimeOffset CreatedDate { get; set; }
        public System.DateTimeOffset timestamp { get; set; }
        public string ConfidenceLevel { get; set; }
        public Nullable<int> ConfidenceLevelID { get; set; }
        public string notes { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
    
        public virtual THREATCAMPAIGN THREATCAMPAIGN { get; set; }
        public virtual THREATCAMPAIGN THREATCAMPAIGN1 { get; set; }
    }
}
