//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTHREATModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class THREATINTENDEDEFFECT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THREATINTENDEDEFFECT()
        {
            this.THREATINTENDEDEFFECTFORINCIDENT = new HashSet<THREATINTENDEDEFFECTFORINCIDENT>();
            this.THREATINTENDEDEFFECTFORTHREATACTORTTP = new HashSet<THREATINTENDEDEFFECTFORTHREATACTORTTP>();
            this.THREATINTENDEDEFFECTFORTHREATCAMPAIGN = new HashSet<THREATINTENDEDEFFECTFORTHREATCAMPAIGN>();
        }
    
        public int ThreatIntendedEffectID { get; set; }
        public string ThreatIntendedEffectGUID { get; set; }
        public string IntendedEffectName { get; set; }
        public string IntendedEffectDescription { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THREATINTENDEDEFFECTFORINCIDENT> THREATINTENDEDEFFECTFORINCIDENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THREATINTENDEDEFFECTFORTHREATACTORTTP> THREATINTENDEDEFFECTFORTHREATACTORTTP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THREATINTENDEDEFFECTFORTHREATCAMPAIGN> THREATINTENDEDEFFECTFORTHREATCAMPAIGN { get; set; }
    }
}
