//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTHREATModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class THREATCAMPAIGNNAMEFORTHREATCAMPAIGN
    {
        public int ThreatCampaignThreatCampaignNameID { get; set; }
        public int ThreatCampaignID { get; set; }
        public int ThreatCampaignNameID { get; set; }
        public System.DateTimeOffset CreatedDate { get; set; }
        public Nullable<int> CreationObjectID { get; set; }
        public System.DateTimeOffset timestamp { get; set; }
        public System.DateTimeOffset ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
        public Nullable<int> VocabularyID { get; set; }
    
        public virtual THREATCAMPAIGN THREATCAMPAIGN { get; set; }
        public virtual THREATCAMPAIGNNAME THREATCAMPAIGNNAME { get; set; }
    }
}
