//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XTHREATModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class THREATACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THREATACTION()
        {
            this.THREATACTIONFORINCIDENT = new HashSet<THREATACTIONFORINCIDENT>();
        }
    
        public int ThreatActionID { get; set; }
        public int ThreatActionCategoryID { get; set; }
        public string ThreatActionCategoryName { get; set; }
        public string ThreatActionName { get; set; }
        public Nullable<System.DateTimeOffset> CreatedDate { get; set; }
        public Nullable<System.DateTimeOffset> timestamp { get; set; }
        public string notes { get; set; }
        public string target { get; set; }
        public Nullable<int> AssetID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> PhysicalLocationID { get; set; }
        public Nullable<int> ThreatActionTargetID { get; set; }
        public Nullable<int> ThreatActionLocationID { get; set; }
        public Nullable<int> VocabularyID { get; set; }
        public Nullable<System.DateTimeOffset> ValidFromDate { get; set; }
        public Nullable<System.DateTimeOffset> ValidUntilDate { get; set; }
        public Nullable<bool> isEncrypted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THREATACTIONFORINCIDENT> THREATACTIONFORINCIDENT { get; set; }
    }
}
